export const kanjiList: [kanji: string, on: string[], kun: string[]][] = [
  ["亜", ["a"], []],
  ["哀", ["ai"], ["awa(re)", "awa(remu)"]],
  ["挨", ["ai"], []],
  ["愛", ["ai"], []],
  ["曖", ["ai"], []],
  ["悪", ["aku", "o"], ["waru(i)"]],
  ["握", ["aku"], ["nigi(ru)"]],
  ["圧", ["atsu"], []],
  ["扱", [], ["atsuka(u)"]],
  ["宛", [], ["a(teru)"]],
  ["嵐", [], ["arashi"]],
  ["安", ["an"], ["yasu(i)"]],
  ["案", ["an"], []],
  ["暗", ["an"], ["kura(i)"]],
  ["以", ["i"], []],
  ["衣", ["i"], ["koromo"]],
  ["位", ["i"], ["kurai"]],
  ["囲", ["i"], ["kako(mu)", "kako(u)"]],
  ["医", ["i"], []],
  ["依", ["i", "e"], []],
  ["委", ["i"], ["yuda(neru)"]],
  ["威", ["i"], []],
  ["為", ["i"], []],
  ["畏", ["i"], ["oso(reru)"]],
  ["胃", ["i"], []],
  ["尉", ["i"], []],
  ["異", ["i"], ["koto(naru)"]],
  ["移", ["i"], ["utsu(ru)", "utsu(su)"]],
  ["萎", ["i"], ["na(eru)"]],
  ["偉", ["i"], ["era(i)"]],
  ["椅", ["i"], []],
  ["彙", ["i"], []],
  ["意", ["i"], []],
  ["違", ["i"], ["chiga(u)", "chiga(eru)"]],
  ["維", ["i"], []],
  ["慰", ["i"], ["nagusa(meru)", "nagusa(mu)"]],
  ["遺", ["i", "yui"], []],
  ["緯", ["i"], []],
  ["域", ["iki"], []],
  ["育", ["iku"], ["soda(tsu)", "soda(teru)", "haguku(mu)"]],
  ["一", ["ichi", "itsu"], ["hito", "hito(tsu)"]],
  ["壱", ["ichi"], []],
  ["逸", ["itsu"], []],
  ["茨", [], ["[ibara]"]],
  ["芋", [], ["imo"]],
  ["引", ["in"], ["hi(ku)", "hi(keru)"]],
  ["印", ["in"], ["shirushi"]],
  ["因", ["in"], ["yo(ru)"]],
  ["咽", ["in"], []],
  ["姻", ["in"], []],
  ["員", ["in"], []],
  ["院", ["in"], []],
  ["淫", ["in"], ["mida(ra)"]],
  ["陰", ["in"], ["kage", "kage(ru)"]],
  ["飲", ["in"], ["no(mu)"]],
  ["隠", ["in"], ["kaku(su)", "kaku(reru)"]],
  ["韻", ["in"], []],
  ["右", ["u", "yuu"], ["migi"]],
  ["宇", ["u"], []],
  ["羽", ["u"], ["ha", "hane"]],
  ["雨", ["u"], ["ame", "[ama]"]],
  ["唄", [], ["[uta]"]],
  ["鬱", ["utsu"], []],
  ["畝", [], ["une"]],
  ["浦", [], ["ura"]],
  ["運", ["un"], ["hako(bu)"]],
  ["雲", ["un"], ["kumo"]],
  ["永", ["ei"], ["naga(i)"]],
  ["泳", ["ei"], ["oyo(gu)"]],
  ["英", ["ei"], []],
  ["映", ["ei"], ["utsu(ru)", "utsu(su)", "ha(eru)"]],
  ["栄", ["ei"], ["saka(eru)", "ha(e)", "ha(eru)"]],
  ["営", ["ei"], ["itona(mu)"]],
  ["詠", ["ei"], ["yo(mu)"]],
  ["影", ["ei"], ["kage"]],
  ["鋭", ["ei"], ["surudo(i)"]],
  ["衛", ["ei"], []],
  ["易", ["i", "eki"], ["yasa(shii)"]],
  ["疫", ["eki", "[yaku]"], []],
  ["益", ["eki", "[yaku]"], []],
  ["液", ["eki"], []],
  ["駅", ["eki"], []],
  ["悦", ["etsu"], []],
  ["越", ["etsu"], ["ko(su)", "ko(eru)"]],
  ["謁", ["etsu"], []],
  ["閲", ["etsu"], []],
  ["円", ["en"], ["maru(i)"]],
  ["延", ["en"], ["no(biru)", "no(beru)", "no(basu)"]],
  ["沿", ["en"], ["so(u)"]],
  ["炎", ["en"], ["honoo"]],
  ["怨", ["en", "on"], []],
  ["宴", ["en"], []],
  ["媛", ["en"], []],
  ["援", ["en"], []],
  ["園", ["en"], ["sono"]],
  ["煙", ["en"], ["kemu(ru)", "kemuri", "kemu(i)"]],
  ["猿", ["en"], ["saru"]],
  ["遠", ["en", "[on]"], ["too(i)"]],
  ["鉛", ["en"], ["namari"]],
  ["塩", ["en"], ["shio"]],
  ["演", ["en"], []],
  ["縁", ["en"], ["fuchi"]],
  ["艶", ["en"], ["tsuya"]],
  [
    "汚",
    ["o"],
    [
      "kega(su)",
      "kega(reru)",
      "kega(rawashii)",
      "yogo(su)",
      "yogo(reru)",
      "kitana(i)",
    ],
  ],
  ["王", ["oo"], []],
  ["凹", ["oo"], []],
  ["央", ["oo"], []],
  ["応", ["oo"], ["kota(eru)"]],
  ["往", ["oo"], []],
  ["押", ["oo"], ["o(su)", "o(saeru)"]],
  ["旺", ["oo"], []],
  ["欧", ["oo"], []],
  ["殴", ["oo"], ["nagu(ru)"]],
  ["桜", ["oo"], ["sakura"]],
  ["翁", ["oo"], []],
  ["奥", ["oo"], ["oku"]],
  ["横", ["oo"], ["yoko"]],
  ["岡", [], ["[oka]"]],
  ["屋", ["oku"], ["ya"]],
  ["億", ["oku"], []],
  ["憶", ["oku"], []],
  ["臆", ["oku"], []],
  ["虞", [], ["osore"]],
  ["乙", ["otsu"], []],
  ["俺", [], ["ore"]],
  ["卸", [], ["oro(su)", "oroshi"]],
  ["音", ["on", "in"], ["oto", "ne"]],
  ["恩", ["on"], []],
  ["温", ["on"], ["atata(ka)", "atata(kai)", "atata(maru)", "atata(meru)"]],
  ["穏", ["on"], ["oda(yaka)"]],
  [
    "下",
    ["ka", "ge"],
    [
      "shita",
      "shimo",
      "moto",
      "sa(geru)",
      "sa(garu)",
      "kuda(ru)",
      "kuda(su)",
      "kuda(saru)",
      "o(rosu)",
      "o(riru)",
    ],
  ],
  ["化", ["ka", "ke"], ["ba(keru)", "ba(kasu)"]],
  ["火", ["ka"], ["hi", "[ho]"]],
  ["加", ["ka"], ["kuwa(eru)", "kuwa(waru)"]],
  ["可", ["ka"], []],
  ["仮", ["ka", "[ke]"], ["kari"]],
  ["何", ["ka"], ["nani", "[nan]"]],
  ["花", ["ka"], ["hana"]],
  ["佳", ["ka"], []],
  ["価", ["ka"], ["atai"]],
  ["果", ["ka"], ["ha(tasu)", "ha(teru)", "ha(te)"]],
  ["河", ["ka"], ["kawa"]],
  ["苛", ["ka"], []],
  ["科", ["ka"], []],
  ["架", ["ka"], ["ka(keru)", "ka(karu)"]],
  ["夏", ["ka", "[ge]"], ["natsu"]],
  ["家", ["ka", "ke"], ["ie", "ya"]],
  ["荷", ["ka"], ["ni"]],
  ["華", ["ka", "[ke]"], ["hana"]],
  ["菓", ["ka"], []],
  ["貨", ["ka"], []],
  ["渦", ["ka"], ["uzu"]],
  ["過", ["ka"], ["su(giru)", "su(gosu)", "ayama(tsu)", "ayama(chi)"]],
  ["嫁", ["ka"], ["yome", "totsu(gu)"]],
  ["暇", ["ka"], ["hima"]],
  ["禍", ["ka"], []],
  ["靴", ["ka"], ["kutsu"]],
  ["寡", ["ka"], []],
  ["歌", ["ka"], ["uta", "uta(u)"]],
  ["箇", ["ka"], []],
  ["稼", ["ka"], ["kase(gu)"]],
  ["課", ["ka"], []],
  ["蚊", [], ["ka"]],
  ["牙", ["ga", "[ge]"], ["kiba"]],
  ["瓦", ["ga"], ["kawara"]],
  ["我", ["ga"], ["ware", "wa"]],
  ["画", ["ga", "kaku"], []],
  ["芽", ["ga"], ["me"]],
  ["賀", ["ga"], []],
  ["雅", ["ga"], []],
  ["餓", ["ga"], []],
  ["介", ["kai"], []],
  ["回", ["kai", "[e]"], ["mawa(ru)", "mawa(su)"]],
  ["灰", ["kai"], ["hai"]],
  ["会", ["kai", "e"], ["a(u)"]],
  ["快", ["kai"], ["kokoroyo(i)"]],
  ["戒", ["kai"], ["imashi(meru)"]],
  ["改", ["kai"], ["arata(meru)", "arata(maru)"]],
  ["怪", ["kai"], ["aya(shii)", "aya(shimu)"]],
  ["拐", ["kai"], []],
  ["悔", ["kai"], ["ku(iru)", "ku(yamu)", "kuya(shii)"]],
  ["海", ["kai"], ["umi"]],
  ["界", ["kai"], []],
  ["皆", ["kai"], ["mina"]],
  ["械", ["kai"], []],
  ["絵", ["kai", "e"], []],
  ["開", ["kai"], ["hira(ku)", "hira(keru)", "a(ku)", "a(keru)"]],
  ["階", ["kai"], []],
  ["塊", ["kai"], ["katamari"]],
  ["楷", ["kai"], []],
  ["解", ["kai", "ge"], ["to(ku)", "to(kasu)", "to(keru)"]],
  ["潰", ["kai"], ["tsubu(su)", "tsubu(reru)"]],
  ["壊", ["kai"], ["kowa(su)", "kowa(reru)"]],
  [
    "懐",
    ["kai"],
    ["futokoro", "natsu(kashii)", "natsu(kashimu)", "natsu(ku)", "natsu(keru)"],
  ],
  ["諧", ["kai"], []],
  ["貝", [], ["kai"]],
  ["外", ["gai", "ge"], ["soto", "hoka", "ha(zusu)", "hazu(reru)"]],
  ["劾", ["gai"], []],
  ["害", ["gai"], []],
  ["崖", ["gai"], ["gake"]],
  ["涯", ["gai"], []],
  ["街", ["gai", "[kai]"], ["machi"]],
  ["慨", ["gai"], []],
  ["蓋", ["gai"], ["futa"]],
  ["該", ["gai"], []],
  ["概", ["gai"], []],
  ["骸", ["gai"], []],
  ["垣", [], ["kaki"]],
  ["柿", [], ["kaki"]],
  ["各", ["kaku"], ["onoono"]],
  ["角", ["kaku"], ["kado", "tsuno"]],
  ["拡", ["kaku"], []],
  ["革", ["kaku"], ["kawa"]],
  ["格", ["kaku", "[koo]"], []],
  ["核", ["kaku"], []],
  ["殻", ["kaku"], ["kara"]],
  ["郭", ["kaku"], []],
  ["覚", ["kaku"], ["obo(eru)", "sa(masu)", "sa(meru)"]],
  ["較", ["kaku"], []],
  ["隔", ["kaku"], ["heda(teru)", "heda(taru)"]],
  ["閣", ["kaku"], []],
  ["確", ["kaku"], ["tashi(ka)", "tashi(kameru)"]],
  ["獲", ["kaku"], ["e(ru)"]],
  ["嚇", ["kaku"], []],
  ["穫", ["kaku"], []],
  ["学", ["gaku"], ["mana(bu)"]],
  ["岳", ["gaku"], ["take"]],
  ["楽", ["gaku", "raku"], ["tano(shii)", "tano(shimu)"]],
  ["額", ["gaku"], ["hitai"]],
  ["顎", ["gaku"], ["ago"]],
  ["掛", [], ["ka(keru)", "ka(karu)", "kakari"]],
  ["潟", [], ["kata"]],
  ["括", ["katsu"], []],
  ["活", ["katsu"], []],
  ["喝", ["katsu"], []],
  ["渇", ["katsu"], ["kawa(ku)"]],
  ["割", ["katsu"], ["wa(ru)", "wari", "wa(reru)", "sa(ku)"]],
  ["葛", ["katsu"], ["kuzu"]],
  ["滑", ["katsu", "kotsu"], ["sube(ru)", "name(raka)"]],
  ["褐", ["katsu"], []],
  ["轄", ["katsu"], []],
  ["且", [], ["ka(tsu)"]],
  ["株", [], ["kabu"]],
  ["釜", [], ["kama"]],
  ["鎌", [], ["kama"]],
  ["刈", [], ["ka(ru)"]],
  ["干", ["kan"], ["ho(su)", "hi(ru)"]],
  ["刊", ["kan"], []],
  ["甘", ["kan"], ["ama(i)", "ama(eru)", "ama(yakasu)"]],
  ["汗", ["kan"], ["ase"]],
  ["缶", ["kan"], []],
  ["完", ["kan"], []],
  ["肝", ["kan"], ["kimo"]],
  ["官", ["kan"], []],
  ["冠", ["kan"], ["kanmuri"]],
  ["巻", ["kan"], ["ma(ku)", "maki"]],
  ["看", ["kan"], []],
  ["陥", ["kan"], ["ochii(ru)", "otoshii(reru)"]],
  ["乾", ["kan"], ["kawa(ku)", "kawa(kasu)"]],
  ["勘", ["kan"], []],
  ["患", ["kan"], ["wazura(u)"]],
  ["貫", ["kan"], ["tsuranu(ku)"]],
  ["寒", ["kan"], ["samu(i)"]],
  ["喚", ["kan"], []],
  ["堪", ["kan"], ["ta(eru)"]],
  ["換", ["kan"], ["ka(eru)", "ka(waru)"]],
  ["敢", ["kan"], []],
  ["棺", ["kan"], []],
  ["款", ["kan"], []],
  ["間", ["kan", "ken"], ["aida", "ma"]],
  ["閑", ["kan"], []],
  ["勧", ["kan"], ["susu(meru)"]],
  ["寛", ["kan"], []],
  ["幹", ["kan"], ["miki"]],
  ["感", ["kan"], []],
  ["漢", ["kan"], []],
  ["慣", ["kan"], ["na(reru)", "na(rasu)"]],
  ["管", ["kan"], ["kuda"]],
  ["関", ["kan"], ["seki", "kaka(waru)"]],
  ["歓", ["kan"], []],
  ["監", ["kan"], []],
  ["緩", ["kan"], ["yuru(i)", "yuru(yaka)", "yuru(mu)", "yuru(meru) "]],
  ["憾", ["kan"], []],
  ["還", ["kan"], []],
  ["館", ["kan"], ["yakata"]],
  ["環", ["kan"], []],
  ["簡", ["kan"], []],
  ["観", ["kan"], []],
  ["韓", ["kan"], []],
  ["艦", ["kan"], []],
  ["鑑", ["kan"], ["kanga(miru)"]],
  ["丸", ["gan"], ["maru", "maru(i)", "maru(meru)"]],
  ["含", ["gan"], ["fuku(mu)", "fuku(meru)"]],
  ["岸", ["gan"], ["kishi"]],
  ["岩", ["gan"], ["iwa"]],
  ["玩", ["gan"], []],
  ["眼", ["gan", "[gen]"], ["manako"]],
  ["頑", ["gan"], []],
  ["顔", ["gan"], ["kao"]],
  ["願", ["gan"], ["nega(u)"]],
  ["企", ["ki"], ["kuwada(teru)"]],
  ["伎", ["ki"], []],
  ["危", ["ki"], ["abu(nai)", "aya(ui)", "aya(bumu)"]],
  ["机", ["ki"], ["tsukue"]],
  ["気", ["ki", "ke"], []],
  ["岐", ["ki"], []],
  ["希", ["ki"], []],
  ["忌", ["ki"], ["i(mu)", "i(mawashii)"]],
  ["汽", ["ki"], []],
  ["奇", ["ki"], []],
  ["祈", ["ki"], ["ino(ru)"]],
  ["季", ["ki"], []],
  ["紀", ["ki"], []],
  ["軌", ["ki"], []],
  ["既", ["ki"], ["sude(ni)"]],
  ["記", ["ki"], ["shiru(su)"]],
  ["起", ["ki"], ["o(kiru)", "o(koru)", "o(kosu)"]],
  ["飢", ["ki"], ["u(eru)"]],
  ["鬼", ["ki"], ["oni"]],
  ["帰", ["ki"], ["kae(ru)", "kae(su)"]],
  ["基", ["ki"], ["moto", "motoi"]],
  ["寄", ["ki"], ["yo(ru)", "yo(seru)"]],
  ["規", ["ki"], []],
  ["亀", ["ki"], ["kame"]],
  ["喜", ["ki"], ["yoroko(bu)"]],
  ["幾", ["ki"], ["iku"]],
  ["揮", ["ki"], []],
  ["期", ["ki", "[go]"], []],
  ["棋", ["ki"], []],
  ["貴", ["ki"], ["tatto(i)", "tooto(i)", "tatto(bu)", "tooto(bu)"]],
  ["棄", ["ki"], []],
  ["毀", ["ki"], []],
  ["旗", ["ki"], ["hata"]],
  ["器", ["ki"], ["utsuwa"]],
  ["畿", ["ki"], []],
  ["輝", ["ki"], ["kagaya(ku)"]],
  ["機", ["ki"], ["hata"]],
  ["騎", ["ki"], []],
  ["技", ["gi"], ["waza"]],
  ["宜", ["gi"], []],
  ["偽", ["gi"], ["itsuwa(ru)", "nise"]],
  ["欺", ["gi"], ["azamu(ku)"]],
  ["義", ["gi"], []],
  ["疑", ["gi"], ["utaga(u)"]],
  ["儀", ["gi"], []],
  ["戯", ["gi"], ["tawamu(reru)"]],
  ["擬", ["gi"], []],
  ["犠", ["gi"], []],
  ["議", ["gi"], []],
  ["菊", ["kiku"], []],
  ["吉", ["kichi", "kitsu"], []],
  ["喫", ["kitsu"], []],
  ["詰", ["kitsu"], ["tsu(meru)", "tsu(maru)", "tsu(mu)"]],
  ["却", ["kyaku"], []],
  ["客", ["kyaku", "kaku"], []],
  ["脚", ["kyaku", "[kya]"], ["ashi"]],
  ["逆", ["gyaku"], ["saka", "saka(rau)"]],
  ["虐", ["gyaku"], ["shiita(geru)"]],
  ["九", ["kyuu", "ku"], ["kokono", "kokono(tsu)"]],
  ["久", ["kyuu", "[ku]"], ["hisa(shii)"]],
  ["及", ["kyuu"], ["oyo(bu)", "oyo(bi)", "oyo(bosu)"]],
  ["弓", ["kyuu"], ["yumi"]],
  ["丘", ["kyuu"], ["oka"]],
  ["旧", ["kyuu"], []],
  ["休", ["kyuu"], ["yasu(mu)", "yasu(maru)", "yasu(meru)"]],
  ["吸", ["kyuu"], ["su(u)"]],
  ["朽", ["kyuu"], ["ku(chiru)"]],
  ["臼", ["kyuu"], ["usu"]],
  ["求", ["kyuu"], ["moto(meru)"]],
  ["究", ["kyuu"], ["kiwa(meru)"]],
  ["泣", ["kyuu"], ["na(ku)"]],
  ["急", ["kyuu"], ["iso(gu)"]],
  ["級", ["kyuu"], []],
  ["糾", ["kyuu"], []],
  ["宮", ["kyuu", "guu", "[ku]"], ["miya"]],
  ["救", ["kyuu"], ["suku(u)"]],
  ["球", ["kyuu"], ["tama"]],
  ["給", ["kyuu"], []],
  ["嗅", ["kyuu"], ["ka(gu)"]],
  ["窮", ["kyuu"], ["kiwa(meru)", "kiwa(maru)"]],
  ["牛", ["gyuu"], ["ushi"]],
  ["去", ["kyo", "ko"], ["sa(ru)"]],
  ["巨", ["kyo"], []],
  ["居", ["kyo"], ["i(ru)"]],
  ["拒", ["kyo"], ["koba(mu)"]],
  ["拠", ["kyo", "ko"], []],
  ["挙", ["kyo"], ["a(geru)", "a(garu)"]],
  ["虚", ["kyo", "[ko]"], []],
  ["許", ["kyo"], ["yuru(su)"]],
  ["距", ["kyo"], []],
  ["魚", ["gyo"], ["uo", "sakana"]],
  ["御", ["gyo", "go"], ["on"]],
  ["漁", ["gyo", "ryoo"], []],
  ["凶", ["kyoo"], []],
  ["共", ["kyoo"], ["tomo"]],
  ["叫", ["kyoo"], ["sake(bu)"]],
  ["狂", ["kyoo"], ["kuru(u)", "kuru(oshii)"]],
  ["京", ["kyoo", "kei"], []],
  ["享", ["kyoo"], []],
  ["供", ["kyoo", "[ku]"], ["sona(eru)", "tomo"]],
  ["協", ["kyoo"], []],
  ["況", ["kyoo"], []],
  ["峡", ["kyoo"], []],
  ["挟", ["kyoo"], ["hasa(mu)", "hasa(maru)"]],
  ["狭", ["kyoo"], ["sema(i)", "saba(meru)", "seba(maru)"]],
  ["恐", ["kyoo"], ["oso(reru)", "oso(roshii)"]],
  ["恭", ["kyoo"], ["uyauya(shii)"]],
  ["胸", ["kyoo"], ["mune", "[muna]"]],
  ["脅", ["kyoo"], ["obiya(kasu)", "odo(su)", "odo(kasu)"]],
  [
    "強",
    ["kyoo", "goo"],
    ["tsuyo(i)", "tsuyo(maru)", "tsuyo(meru)", "shi(iru)"],
  ],
  ["教", ["kyoo"], ["oshi(eru)", "oso(waru)"]],
  ["郷", ["kyoo", "goo"], []],
  ["境", ["kyoo", "[kei]"], ["sakai"]],
  ["橋", ["kyoo"], ["hashi"]],
  ["矯", ["kyoo"], ["ta(meru)"]],
  ["鏡", ["kyoo"], ["kagami"]],
  ["競", ["kyoo", "kei"], ["kiso(u)", "se(ru)"]],
  ["響", ["kyoo"], ["hibi(ku)"]],
  ["驚", ["kyoo"], ["odoro(ku)", "odoro(kasu)"]],
  ["仰", ["gyoo", "[koo]"], ["ao(gu)", "oo(se)"]],
  ["暁", ["gyoo"], ["akatsuki"]],
  ["業", ["gyoo", "goo"], ["waza"]],
  ["凝", ["gyoo"], ["ko(ru)", "ko(rasu)"]],
  ["曲", ["kyoku"], ["ma(garu)", "ma(geru)"]],
  ["局", ["kyoku"], []],
  ["極", ["kyoku", "goku"], ["kiwa(meru)", "kiwa(maru)", "kiwa(mi)"]],
  ["玉", ["gyoku"], ["tama"]],
  ["巾", ["kin"], []],
  ["斤", ["kin"], []],
  ["均", ["kin"], []],
  ["近", ["kin"], ["chika(i)"]],
  ["金", ["kin", "kon"], ["kane", "[kana]"]],
  ["菌", ["kin"], []],
  ["勤", ["kin", "[gon]"], ["tsuto(meru)", "tsuto(maru)"]],
  ["琴", ["kin"], ["koto"]],
  ["筋", ["kin"], ["suji"]],
  ["僅", ["kin"], ["wazu(ka)"]],
  ["禁", ["kin"], []],
  ["緊", ["kin"], []],
  ["錦", ["kin"], ["nishiki"]],
  ["謹", ["kin"], ["tsutsushi(mu)"]],
  ["襟", ["kin"], ["eri"]],
  ["吟", ["gin"], []],
  ["銀", ["gin"], []],
  ["区", ["ku"], []],
  ["句", ["ku"], []],
  [
    "苦",
    ["ku"],
    ["kuru(shii)", "kuru(shimu)", "kuru(shimeru)", "niga(i)", "niga(ru)"],
  ],
  ["駆", ["ku"], ["ka(keru)", "ka(ru)"]],
  ["具", ["gu"], []],
  ["惧", ["gu"], []],
  ["愚", ["gu"], ["oro(ka)"]],
  ["空", ["kuu"], ["sora", "a(ku)", "a(keru)", "kara"]],
  ["偶", ["guu"], []],
  ["遇", ["guu"], []],
  ["隅", ["guu"], ["sumi"]],
  ["串", [], ["kushi"]],
  ["屈", ["kutsu"], []],
  ["掘", ["kutsu"], ["ho(ru)"]],
  ["窟", ["kutsu"], []],
  ["熊", [], ["kuma"]],
  ["繰", [], ["ku(ru)"]],
  ["君", ["kun"], ["kimi"]],
  ["訓", ["kun"], []],
  ["勲", ["kun"], []],
  ["薫", ["kun"], ["kao(ru)"]],
  ["軍", ["gun"], []],
  ["郡", ["gun"], []],
  ["群", ["gun"], ["mu(reru)", "mu(re)", "[mura]"]],
  ["兄", ["kei", "[kyoo]"], ["ani"]],
  ["刑", ["kei"], []],
  ["形", ["kei", "gyoo"], ["kata", "katachi"]],
  ["系", ["kei"], []],
  ["径", ["kei"], []],
  ["茎", ["kei"], ["kuki"]],
  ["係", ["kei"], ["kaka(ru)", "kakari"]],
  ["型", ["kei"], ["kata"]],
  ["契", ["kei"], ["chigi(ru)"]],
  ["計", ["kei"], ["haka(ru)", "haka(rau)"]],
  ["恵", ["kei", "e"], ["megu(mu)"]],
  ["啓", ["kei"], []],
  ["掲", ["kei"], ["kaka(geru)"]],
  ["渓", ["kei"], []],
  ["経", ["kei", "kyoo"], ["he(ru)"]],
  ["蛍", ["kei"], ["hotaru"]],
  ["敬", ["kei"], ["uyama(u)"]],
  ["景", ["kei"], []],
  ["軽", ["kei"], ["karu(i)", "karo(yaka)"]],
  ["傾", ["kei"], ["katamu(ku)", "katamu(keru)"]],
  ["携", ["kei"], ["tazusa(eru)", "tazusa(waru)"]],
  ["継", ["kei"], ["tsu(gu)"]],
  ["詣", ["kei"], ["mou(deru)"]],
  ["慶", ["kei"], []],
  ["憬", ["kei"], []],
  ["稽", ["kei"], []],
  ["憩", ["kei"], ["iko(i)", "iko(u)"]],
  ["警", ["kei"], []],
  ["鶏", ["kei"], ["niwatori"]],
  ["芸", ["gei"], []],
  ["迎", ["gei"], ["muka(eru)"]],
  ["鯨", ["gei"], ["kujira"]],
  ["隙", ["geki"], ["suki"]],
  ["劇", ["geki"], []],
  ["撃", ["geki"], ["u(tsu)"]],
  ["激", ["geki"], ["hage(shii)"]],
  ["桁", [], ["keta"]],
  ["欠", ["ketsu"], ["ka(keru)", "ka(ku)"]],
  ["穴", ["ketsu"], ["ana"]],
  ["血", ["ketsu"], ["chi"]],
  ["決", ["ketsu"], ["ki(meru)", "ki(maru)"]],
  ["結", ["ketsu"], ["musu(bu)", "yu(u)", "yu(waeru)"]],
  ["傑", ["ketsu"], []],
  ["潔", ["ketsu"], ["isagiyo(i)"]],
  ["月", ["getsu", "gatsu"], ["tsuki"]],
  ["犬", ["ken"], ["inu"]],
  ["件", ["ken"], []],
  ["見", ["ken"], ["mi(ru)", "mi(eru)", "mi(seru)"]],
  ["券", ["ken"], []],
  ["肩", ["ken"], ["kata"]],
  ["建", ["ken", "[kon]"], ["ta(teru)", "ta(tsu)"]],
  ["研", ["ken"], ["to(gu)"]],
  ["県", ["ken"], []],
  ["倹", ["ken"], []],
  ["兼", ["ken"], ["ka(neru)"]],
  ["剣", ["ken"], ["tsurugi"]],
  ["拳", ["ken"], ["kobushi"]],
  ["軒", ["ken"], ["noki"]],
  ["健", ["ken"], ["suko(yaka)"]],
  ["険", ["ken"], ["kewa(shii)"]],
  ["圏", ["ken"], []],
  ["堅", ["ken"], ["kata(i)"]],
  ["検", ["ken"], []],
  ["嫌", ["ken", "[gen]"], ["kira(u)", "iya"]],
  ["献", ["ken", "[kon]"], []],
  ["絹", ["ken"], ["kinu"]],
  ["遣", ["ken"], ["tsuka(u)", "tsuka(wasu)"]],
  ["権", ["ken", "[gon]"], []],
  ["憲", ["ken"], []],
  ["賢", ["ken"], ["kashiko(i)"]],
  ["謙", ["ken"], []],
  ["鍵", ["ken"], ["kagi"]],
  ["繭", ["ken"], ["mayu"]],
  ["顕", ["ken"], []],
  ["験", ["ken", "[gen]"], []],
  ["懸", ["ken", "[ke]"], ["ka(keru)", "ka(karu)"]],
  ["元", ["gen", "gan"], ["moto"]],
  ["幻", ["gen"], ["maboroshi"]],
  ["玄", ["gen"], []],
  ["言", ["gen", "gon"], ["i(u)", "koto"]],
  ["弦", ["gen"], ["tsuru"]],
  ["限", ["gen"], ["kagi(ru)"]],
  ["原", ["gen"], ["hara"]],
  ["現", ["gen"], ["arawa(reru)", "arawa(su)"]],
  ["舷", ["gen"], []],
  ["減", ["gen"], ["he(ru)", "he(rasu)"]],
  ["源", ["gen"], ["minamoto"]],
  ["厳", ["gen", "[gon]"], ["ogoso(ka)", "kibi(shii)"]],
  ["己", ["ko", "ki"], ["onore"]],
  ["戸", ["ko"], ["to"]],
  ["古", ["ko"], ["furu(i)", "furu(su)"]],
  ["呼", ["ko"], ["yo(bu)"]],
  ["固", ["ko"], ["kata(meru)", "kata(maru)", "kata(i)"]],
  ["股", ["ko"], ["mata"]],
  ["虎", ["ko"], ["tora"]],
  ["孤", ["ko"], []],
  ["弧", ["ko"], []],
  ["故", ["ko"], ["yue"]],
  ["枯", ["ko"], ["ka(reru)", "ka(rasu)"]],
  ["個", ["ko"], []],
  ["庫", ["ko", "[ku]"], []],
  ["湖", ["ko"], ["mizuumi"]],
  ["雇", ["ko"], ["yato(u)"]],
  ["誇", ["ko"], ["hoko(ru)"]],
  ["鼓", ["ko"], ["tsuzumi"]],
  ["錮", ["ko"], []],
  ["顧", ["ko"], ["kaeri(miru)"]],
  ["五", ["go"], ["itsu", "itsu(tsu)"]],
  ["互", ["go"], ["taga(i)"]],
  ["午", ["go"], []],
  ["呉", ["go"], []],
  ["後", ["go", "koo"], ["nochi", "ushi(ro)", "ato", "oku(reru)"]],
  ["娯", ["go"], []],
  ["悟", ["go"], ["sato(ru)"]],
  ["碁", ["go"], []],
  ["語", ["go"], ["kata(ru)", "kata(rau)"]],
  ["誤", ["go"], ["ayama(ru)"]],
  ["護", ["go"], []],
  ["口", ["koo", "ku"], ["kuchi"]],
  ["工", ["koo", "ku"], []],
  ["公", ["koo"], ["ooyake"]],
  ["勾", ["koo"], []],
  ["孔", ["koo"], []],
  ["功", ["koo", "[ku]"], []],
  ["巧", ["koo"], ["taku(mi)"]],
  [
    "広",
    ["koo"],
    ["hiro(i)", "hiro(maru)", "hiro(meru)", "hiro(garu)", "hiro(geru)"],
  ],
  ["甲", ["koo", "kan"], []],
  [
    "交",
    ["koo"],
    [
      "maji(waru)",
      "maji(eru)",
      "maji(ru)",
      "ma(zaru)",
      "ma(zeru)",
      "ka(u)",
      "ka(wasu)",
    ],
  ],
  ["光", ["koo"], ["hika(ru)", "hikari"]],
  ["向", ["koo"], ["mu(ku)", "mu(keru)", "mu(kau)", "mu(koo)"]],
  ["后", ["koo"], []],
  ["好", ["koo"], ["kono(mu)", "su(ku)"]],
  ["江", ["koo"], ["e"]],
  ["考", ["koo"], ["kanga(eru)"]],
  ["行", ["koo", "gyoo", "[an]"], ["i(ku)", "yu(ku)", "okona(u)"]],
  ["坑", ["koo"], []],
  ["孝", ["koo"], []],
  ["抗", ["koo"], []],
  ["攻", ["koo"], ["se(meru)"]],
  ["更", ["koo"], ["sara", "fu(keru)", "fu(kasu)"]],
  ["効", ["koo"], ["ki(ku)"]],
  ["幸", ["koo"], ["saiwa(i)", "sachi", "shiawa(se)"]],
  ["拘", ["koo"], []],
  ["肯", ["koo"], []],
  ["侯", ["koo"], []],
  ["厚", ["koo"], ["atsu(i)"]],
  ["恒", ["koo"], []],
  ["洪", ["koo"], []],
  ["皇", ["koo", "oo"], []],
  ["紅", ["koo", "[ku]"], ["beni", "kurenai"]],
  ["荒", ["koo"], ["ara(i)", "a(reru)", "a(rasu)"]],
  ["郊", ["koo"], []],
  ["香", ["koo", "[kyoo]"], ["ka", "kao(ri)", "kao(ru)"]],
  ["候", ["koo"], ["sooroo"]],
  ["校", ["koo"], []],
  ["耕", ["koo"], ["tagaya(su)"]],
  ["航", ["koo"], []],
  ["貢", ["koo", "[ku]"], ["mitsu(gu)"]],
  ["降", ["koo"], ["o(riru)", "o(rosu)", "fu(ru)"]],
  ["高", ["koo"], ["taka(i)", "taka", "taka(maru)", "taka(meru)"]],
  ["康", ["koo"], []],
  ["控", ["koo"], ["hika(eru)"]],
  ["梗", ["koo"], []],
  ["黄", ["koo", "oo"], ["ki", "[ko]"]],
  ["喉", ["koo"], ["nodo"]],
  ["慌", ["koo"], ["awa(teru)", "awa(tadashii)"]],
  ["港", ["koo"], ["minato"]],
  ["硬", ["koo"], ["kata(i)"]],
  ["絞", ["koo"], ["shibo(ru)", "shi(meru)", "shi(maru)"]],
  ["項", ["koo"], []],
  ["溝", ["koo"], ["mizo"]],
  ["鉱", ["koo"], []],
  ["構", ["koo"], ["kama(eru)", "kama(u)"]],
  ["綱", ["koo"], ["tsuna"]],
  ["酵", ["koo"], []],
  ["稿", ["koo"], []],
  ["興", ["koo", "kyoo"], ["oko(ru)", "oko(su)"]],
  ["衡", ["koo"], []],
  ["鋼", ["koo"], ["hagane"]],
  ["講", ["koo"], []],
  ["購", ["koo"], []],
  ["乞", [], ["ko(u)"]],
  ["号", ["goo"], []],
  ["合", ["goo", "gaQ", "[kaQ]"], ["a(u)", "a(wasu)", "a(waseru)"]],
  ["拷", ["goo"], []],
  ["剛", ["goo"], []],
  ["傲", ["goo"], []],
  ["豪", ["goo"], []],
  ["克", ["koku"], []],
  ["告", ["koku"], ["tsu(geru)"]],
  ["谷", ["koku"], ["tani"]],
  ["刻", ["koku"], ["kiza(mu)"]],
  ["国", ["koku"], ["kuni"]],
  ["黒", ["koku"], ["kuro", "kuro(i)"]],
  ["穀", ["koku"], []],
  ["酷", ["koku"], []],
  ["獄", ["goku"], []],
  ["骨", ["kotsu"], ["hone"]],
  ["駒", [], ["koma"]],
  ["込", [], ["ko(mu)", "ko(meru)"]],
  ["頃", [], ["koro"]],
  ["今", ["kon", "kin"], ["ima"]],
  ["困", ["kon"], ["koma(ru)"]],
  ["昆", ["kon"], []],
  ["恨", ["kon"], ["ura(mu)", "ura(meshii)"]],
  ["根", ["kon"], ["ne"]],
  ["婚", ["kon"], []],
  ["混", ["kon"], ["ma(jiru)", "ma(zaru)", "ma(zeru)", "ko(mu)"]],
  ["痕", ["kon"], ["ato"]],
  ["紺", ["kon"], []],
  ["魂", ["kon"], ["tamashii"]],
  ["墾", ["kon"], []],
  ["懇", ["kon"], ["nengo(ro)"]],
  ["左", ["sa"], ["hidari"]],
  ["佐", ["sa"], []],
  ["沙", ["sa"], []],
  ["査", ["sa"], []],
  ["砂", ["sa", "sha"], ["suna"]],
  ["唆", ["sa"], ["sosonoka(su)"]],
  ["差", ["sa"], ["sa(su)"]],
  ["詐", ["sa"], []],
  ["鎖", ["sa"], ["kusari"]],
  ["座", ["za"], ["suwa(ru)"]],
  ["挫", ["za"], []],
  ["才", ["sai"], []],
  ["再", ["sai", "[sa]"], ["futata(bi)"]],
  ["災", ["sai"], ["wazawa(i)"]],
  ["妻", ["sai"], ["tsuma"]],
  ["采", ["sai"], []],
  ["砕", ["sai"], ["kuda(ku)", "kuda(keru)"]],
  ["宰", ["sai"], []],
  ["栽", ["sai"], []],
  ["彩", ["sai"], ["irodo(ru)"]],
  ["採", ["sai"], ["to(ru)"]],
  ["済", ["sai"], ["su(mu)", "su(masu)"]],
  ["祭", ["sai"], ["matsu(ru)", "matsu(ri)"]],
  ["斎", ["sai"], []],
  ["細", ["sai"], ["hoso(i)", "hoso(ru)", "koma(ka)", "koma(kai)"]],
  ["菜", ["sai"], ["na"]],
  ["最", ["sai"], ["motto(mo)"]],
  ["裁", ["sai"], ["ta(tsu)", "saba(ku)"]],
  ["債", ["sai"], []],
  ["催", ["sai"], ["moyoo(su)"]],
  ["塞", ["sai", "soku"], ["fusa(gu)", "fusa(garu)"]],
  ["歳", ["sai", "sei"], []],
  ["載", ["sai"], ["no(seru)", "no(ru)"]],
  ["際", ["sai"], ["kiwa"]],
  ["埼", [], ["sai"]],
  ["在", ["zai"], ["a(ru)"]],
  ["材", ["zai"], []],
  ["剤", ["zai"], []],
  ["財", ["zai", "sai"], []],
  ["罪", ["zai"], ["tsumi"]],
  ["崎", [], ["saki"]],
  ["作", ["saku", "sa"], ["tsuku(ru)"]],
  ["削", ["saku"], ["kezu(ru)"]],
  ["昨", ["saku"], []],
  ["柵", ["saku"], []],
  ["索", ["saku"], []],
  ["策", ["saku"], []],
  ["酢", ["saku"], ["su"]],
  ["搾", ["saku"], ["shibo(ru)"]],
  ["錯", ["saku"], []],
  ["咲", [], ["sa(ku)"]],
  ["冊", ["satsu", "saku"], []],
  ["札", ["satsu"], ["fuda"]],
  ["刷", ["satsu"], ["su(ru)"]],
  ["刹", ["satsu", "setsu"], []],
  ["拶", ["satsu"], []],
  ["殺", ["satsu", "[sai]", "[setsu]"], ["koro(su)"]],
  ["察", ["satsu"], []],
  ["撮", ["satsu"], ["to(ru)"]],
  ["擦", ["satsu"], ["su(ru)", "su(reru)"]],
  ["雑", ["zatsu", "zoo"], []],
  ["皿", [], ["sara"]],
  ["三", ["san"], ["mi", "mi(tsu)", "mit(tsu)"]],
  ["山", ["san"], ["yama"]],
  ["参", ["san"], ["mai(ru)"]],
  ["桟", ["san"], []],
  ["蚕", ["san"], ["kaiko"]],
  ["惨", ["san", "zan"], ["miji(me)"]],
  ["産", ["san"], ["u(mu)", "u(mareru)", "ubu"]],
  ["傘", ["san"], ["kasa"]],
  ["散", ["san"], ["chi(ru)", "chi(rasu)", "chi(rakasu)", "chi(rakaru)"]],
  ["算", ["san"], []],
  ["酸", ["san"], ["su(i)"]],
  ["賛", ["san"], []],
  ["残", ["zan"], ["noko(ru)", "noko(su)"]],
  ["斬", ["zan"], ["ki(ru)"]],
  ["暫", ["zan"], []],
  ["士", ["shi"], []],
  ["子", ["shi", "su"], ["ko"]],
  ["支", ["shi"], ["sasa(eru)"]],
  ["止", ["shi"], ["to(maru)", "to(meru)"]],
  ["氏", ["shi"], ["uji"]],
  ["仕", ["shi", "[ji]"], ["tsuka(eru)"]],
  ["史", ["shi"], []],
  ["司", ["shi"], []],
  ["四", ["shi"], ["yo", "yo(tsu)", "yot(tsu)", "yon"]],
  ["市", ["shi"], ["ichi"]],
  ["矢", ["shi"], ["ya"]],
  ["旨", ["shi"], ["mune"]],
  ["死", ["shi"], ["shi(nu)"]],
  ["糸", ["shi"], ["ito"]],
  ["至", ["shi"], ["ita(ru)"]],
  ["伺", ["shi"], ["ukaga(u)"]],
  ["志", ["shi"], ["kokoroza(su)", "kokorozashi"]],
  ["私", ["shi"], ["watakushi", "watashi"]],
  ["使", ["shi"], ["tsuka(u)"]],
  ["刺", ["shi"], ["sa(su)", "sa(saru)"]],
  ["始", ["shi"], ["haji(meru)", "haji(maru)"]],
  ["姉", ["shi"], ["ane"]],
  ["枝", ["shi"], ["eda"]],
  ["祉", ["shi"], []],
  ["肢", ["shi"], []],
  ["姿", ["shi"], ["sugata"]],
  ["思", ["shi"], ["omo(u)"]],
  ["指", ["shi"], ["yubi", "sa(su)"]],
  ["施", ["shi", "se"], ["hodoko(su)"]],
  ["師", ["shi"], []],
  ["恣", ["shi"], []],
  ["紙", ["shi"], ["kami"]],
  ["脂", ["shi"], ["abura"]],
  ["視", ["shi"], []],
  ["紫", ["shi"], ["murasaki"]],
  ["詞", ["shi"], []],
  ["歯", ["shi"], ["ha"]],
  ["嗣", ["shi"], []],
  ["試", ["shi"], ["kokoro(miru)", "tame(su)"]],
  ["詩", ["shi"], []],
  ["資", ["shi"], []],
  ["飼", ["shi"], ["ka(u)"]],
  ["誌", ["shi"], []],
  ["雌", ["shi"], ["me", "mesu"]],
  ["摯", ["shi"], []],
  ["賜", ["shi"], ["tamawa(ru)"]],
  ["諮", ["shi"], ["haka(ru)"]],
  ["示", ["ji", "shi"], ["shime(su)"]],
  ["字", ["ji"], ["aza"]],
  ["寺", ["ji"], ["tera"]],
  ["次", ["ji", "shi"], ["tsu(gu)", "tsugi"]],
  ["耳", ["ji"], ["mimi"]],
  ["自", ["ji", "shi"], ["mizuka(ra)"]],
  ["似", ["ji"], ["ni(ru)"]],
  ["児", ["ji", "[ni]"], []],
  ["事", ["ji", "[zu]"], ["koto"]],
  ["侍", ["ji"], ["samurai"]],
  ["治", ["chi", "ji"], ["osa(meru)", "osa(maru)", "nao(ru)", "nao(su)"]],
  ["持", ["ji"], ["mo(tsu)"]],
  ["時", ["ji"], ["toki"]],
  ["滋", ["ji"], []],
  ["慈", ["ji"], ["itsuku(shimu)"]],
  ["辞", ["ji"], ["ya(meru)"]],
  ["磁", ["ji"], []],
  ["餌", ["ji"], ["esa", "e"]],
  ["璽", ["ji"], []],
  ["鹿", [], ["shika", "[ka]"]],
  ["式", ["shiki"], []],
  ["識", ["shiki"], []],
  ["軸", ["jiku"], []],
  ["七", ["shichi"], ["nana", "nana(tsu)", "[nano]"]],
  ["叱", ["shitsu"], ["shika(ru)"]],
  ["失", ["shitsu"], ["ushina(u)"]],
  ["室", ["shitsu"], ["muro"]],
  ["疾", ["shitsu"], []],
  ["執", ["shitsu", "shuu"], ["to(ru)"]],
  ["湿", ["shitsu"], ["shime(ru)", "shime(su)"]],
  ["嫉", ["shitsu"], []],
  ["漆", ["shitsu"], ["urushi"]],
  ["質", ["shitsu", "shichi", "[chi]"], []],
  ["実", ["jitsu"], ["mi", "mino(ru)"]],
  ["芝", [], ["shiba"]],
  ["写", ["sha"], ["utsu(su)", "utsu(ru)"]],
  ["社", ["sha"], ["yashiro"]],
  ["車", ["sha"], ["kuruma"]],
  ["舎", ["sha"], []],
  ["者", ["sha"], ["mono"]],
  ["射", ["sha"], ["i(ru)"]],
  ["捨", ["sha"], ["su(teru)"]],
  ["赦", ["sha"], []],
  ["斜", ["sha"], ["nana(me)"]],
  ["煮", ["sha"], ["ni(ru)", "ni(eru)", "ni(yasu)"]],
  ["遮", ["sha"], ["saegi(ru)"]],
  ["謝", ["sha"], ["ayama(ru)"]],
  ["邪", ["ja"], []],
  ["蛇", ["ja", "da"], ["hebi"]],
  ["尺", ["shaku"], []],
  ["借", ["shaku"], ["ka(riru)"]],
  ["酌", ["shaku"], ["ku(mu)"]],
  ["釈", ["shaku"], []],
  ["爵", ["shaku"], []],
  ["若", ["jaku", "[nyaku]"], ["waka(i)", "mo(shikuwa)"]],
  ["弱", ["jaku"], ["yowa(i)", "yowa(ru)", "yowa(maru)", "yowa(meru)"]],
  ["寂", ["jaku", "[seki]"], ["sabi", "sabi(shii)", "sabi(reru)"]],
  ["手", ["shu"], ["te", "[ta]"]],
  ["主", ["shu", "[su]"], ["nushi", "omo"]],
  ["守", ["shu", "[su]"], ["mamo(ru)", "mo(ri)"]],
  ["朱", ["shu"], []],
  ["取", ["shu"], ["to(ru)"]],
  ["狩", ["shu"], ["ka(ru)", "ka(ri)"]],
  ["首", ["shu"], ["kubi"]],
  ["殊", ["shu"], ["koto"]],
  ["珠", ["shu"], []],
  ["酒", ["shu"], ["sake", "[saka]"]],
  ["腫", ["shu"], ["ha(reru)", "ha(rasu)"]],
  ["種", ["shu"], ["tane"]],
  ["趣", ["shu"], ["omomuki"]],
  ["寿", ["ju"], ["kotobuki"]],
  ["受", ["ju"], ["u(keru)", "u(karu)"]],
  ["呪", ["ju"], ["noro(u)"]],
  ["授", ["ju"], ["sazu(keru)", "sazu(karu)"]],
  ["需", ["ju"], []],
  ["儒", ["ju"], []],
  ["樹", ["ju"], []],
  ["収", ["shuu"], ["osa(meru)", "osa(maru)"]],
  ["囚", ["shuu"], []],
  ["州", ["shuu"], ["su"]],
  ["舟", ["shuu"], ["fune", "[funa]"]],
  ["秀", ["shuu"], ["hii(deru)"]],
  ["周", ["shuu"], ["mawa(ri)"]],
  ["宗", ["shuu", "soo"], []],
  ["拾", ["shuu", "juu"], ["hiro(u)"]],
  ["秋", ["shuu"], ["aki"]],
  ["臭", ["shuu"], ["kusa(i)", "nio(u)"]],
  ["修", ["shuu", "[shu]"], ["osa(meru)", "osa(maru)"]],
  ["袖", ["shuu"], ["sode"]],
  ["終", ["shuu"], ["o(waru)", "o(eru)"]],
  ["羞", ["shuu"], []],
  ["習", ["shuu"], ["nara(u)"]],
  ["週", ["shuu"], []],
  ["就", ["shuu", "[ju]"], ["tsu(ku)", "tsu(keru)"]],
  ["衆", ["shuu", "[shu]"], []],
  ["集", ["shuu"], ["atsu(maru)", "atsu(meru)", "tsudo(u)"]],
  ["愁", ["shuu"], ["ure(eru)", "ure(i)"]],
  ["酬", ["shuu"], []],
  ["醜", ["shuu"], ["miniku(i)"]],
  ["蹴", ["shuu"], ["ke(ru)"]],
  ["襲", ["shuu"], ["oso(u)"]],
  ["十", ["juu", "jiQ"], ["too", "to"]],
  ["汁", ["juu"], ["shiru"]],
  ["充", ["juu"], ["a(teru)"]],
  ["住", ["juu"], ["su(mu)", "su(mau)"]],
  ["柔", ["juu", "nyuu"], ["yawa(raka)", "yawa(rakai)"]],
  ["重", ["juu", "choo"], ["e", "omo(i)", "kasa(neru)", "kasa(naru)"]],
  ["従", ["juu", "[shoo]", "[ju]"], ["shitaga(u)", "shitaga(eru)"]],
  ["渋", ["juu"], ["shibu", "shibu(i)", "shibu(ru)"]],
  ["銃", ["juu"], []],
  ["獣", ["juu"], ["kemono"]],
  ["縦", ["juu"], ["tate"]],
  ["叔", ["shuku"], []],
  ["祝", ["shuku", "[shuu]"], ["iwa(u)"]],
  ["宿", ["shuku"], ["yado", "yado(ru)", "yado(su)"]],
  ["淑", ["shuku"], []],
  ["粛", ["shuku"], []],
  [
    "縮",
    ["shuku"],
    ["chiji(mu)", "chiji(maru)", "chiji(meru)", "chiji(reru)", "chiji(rasu)"],
  ],
  ["塾", ["juku"], []],
  ["熟", ["juku"], ["u(reru)"]],
  ["出", ["shutsu", "[sui]"], ["de(ru)", "da(su)"]],
  ["述", ["jutsu"], ["no(beru)"]],
  ["術", ["jutsu"], []],
  ["俊", ["shun"], []],
  ["春", ["shun"], ["haru"]],
  ["瞬", ["shun"], ["matata(ku)"]],
  ["旬", ["jun", "[shun]"], []],
  ["巡", ["jun"], ["megu(ru)"]],
  ["盾", ["jun"], ["tate"]],
  ["准", ["jun"], []],
  ["殉", ["jun"], []],
  ["純", ["jun"], []],
  ["循", ["jun"], []],
  ["順", ["jun"], []],
  ["準", ["jun"], []],
  ["潤", ["jun"], ["uruo(u)", "uruo(su)", "uru(mu)"]],
  ["遵", ["jun"], []],
  ["処", ["sho"], []],
  ["初", ["sho"], ["haji(me)", "haji(mete)", "hatsu", "ui", "so(meru)"]],
  ["所", ["sho"], ["tokoro"]],
  ["書", ["sho"], ["ka(ku)"]],
  ["庶", ["sho"], []],
  ["暑", ["sho"], ["atsu(i)"]],
  ["署", ["sho"], []],
  ["緒", ["sho", "[cho]"], ["o"]],
  ["諸", ["sho"], []],
  ["女", ["jo", "nyo", "[nyoo]"], ["onna", "me"]],
  ["如", ["jo", "nyo"], []],
  ["助", ["jo"], ["tasu(keru)", "tasu(karu)", "suke"]],
  ["序", ["jo"], []],
  ["叙", ["jo"], []],
  ["徐", ["jo"], []],
  ["除", ["jo", "[ji]"], ["nozo(ku)"]],
  ["小", ["shoo"], ["chii(sai)", "ko", "o"]],
  ["升", ["shoo"], ["masu"]],
  ["少", ["shoo"], ["suku(nai)", "suko(shi)"]],
  ["召", ["shoo"], ["me(su)"]],
  ["匠", ["shoo"], []],
  ["床", ["shoo"], ["toko", "yuka"]],
  ["抄", ["shoo"], []],
  ["肖", ["shoo"], []],
  ["尚", ["shoo"], []],
  ["招", ["shoo"], ["mane(ku)"]],
  ["承", ["shoo"], ["uketamawa(ru)"]],
  ["昇", ["shoo"], ["nobo(ru)"]],
  ["松", ["shoo"], ["matsu"]],
  ["沼", ["shoo"], ["numa"]],
  ["昭", ["shoo"], []],
  ["宵", ["shoo"], ["yoi"]],
  ["将", ["shoo"], []],
  ["消", ["shoo"], ["ki(eru)", "ke(su)"]],
  ["症", ["shoo"], []],
  ["祥", ["shoo"], []],
  ["称", ["shoo"], []],
  ["笑", ["shoo"], ["wara(u)", "e(mu)"]],
  ["唱", ["shoo"], ["tona(eru)"]],
  ["商", ["shoo"], ["akina(u)"]],
  ["渉", ["shoo"], []],
  ["章", ["shoo"], []],
  ["紹", ["shoo"], []],
  ["訟", ["shoo"], []],
  ["勝", ["shoo"], ["ka(tsu)", "masa(ru)"]],
  ["掌", ["shoo"], []],
  ["晶", ["shoo"], []],
  ["焼", ["shoo"], ["ya(ku)", "ya(keru)"]],
  ["焦", ["shoo"], ["ko(geru)", "ko(gasu)", "ko(gareru)", "ase(ru)"]],
  ["硝", ["shoo"], []],
  ["粧", ["shoo"], []],
  ["詔", ["shoo"], ["mikotonori"]],
  ["証", ["shoo"], []],
  ["象", ["shoo", "zoo"], []],
  ["傷", ["shoo"], ["kizu", "ita(mu)", "ita(meru)"]],
  ["奨", ["shoo"], []],
  ["照", ["shoo"], ["te(ru)", "te(rasu)", "te(reru)"]],
  ["詳", ["shoo"], ["kuwa(shii)"]],
  ["彰", ["shoo"], []],
  ["障", ["shoo"], ["sawa(ru)"]],
  ["憧", ["shoo"], ["akoga(reru)"]],
  ["衝", ["shoo"], []],
  ["賞", ["shoo"], []],
  ["償", ["shoo"], ["tsugu(nau)"]],
  ["礁", ["shoo"], []],
  ["鐘", ["shoo"], ["kane"]],
  [
    "上",
    ["joo", "[shoo]"],
    [
      "ue",
      "[uwa]",
      "kami",
      "a(geru)",
      "a(garu)",
      "nobo(ru)",
      "nobo(seru)",
      "nobo(su)",
    ],
  ],
  ["丈", ["joo"], ["take"]],
  ["冗", ["joo"], []],
  ["条", ["joo"], []],
  ["状", ["joo"], []],
  ["乗", ["joo"], ["no(ru)", "no(seru)"]],
  ["城", ["joo"], ["shiro"]],
  ["浄", ["joo"], []],
  ["剰", ["joo"], []],
  ["常", ["joo"], ["tsune", "toko"]],
  ["情", ["joo", "[sei]"], ["nasa(ke)"]],
  ["場", ["joo"], ["ba"]],
  ["畳", ["joo"], ["tata(mu)", "tatami"]],
  ["蒸", ["joo"], ["mu(su)", "mu(reru)", "mu(rasu)"]],
  ["縄", ["joo"], ["nawa"]],
  ["壌", ["joo"], []],
  ["嬢", ["joo"], []],
  ["錠", ["joo"], []],
  ["譲", ["joo"], ["yuzu(ru)"]],
  ["醸", ["joo"], ["kamo(su)"]],
  ["色", ["shoku", "shiki"], ["iro"]],
  ["拭", ["shoku"], ["fu(ku)", "nugu(u)"]],
  ["食", ["shoku", "[jiki]"], ["ku(u)", "ku(rau)", "ta(beru)"]],
  ["植", ["shoku"], ["u(eru)", "u(waru)"]],
  ["殖", ["shoku"], ["fu(eru)", "fu(yasu)"]],
  ["飾", ["shoku"], ["kaza(ru)"]],
  ["触", ["shoku"], ["fu(reru)", "sawa(ru)"]],
  ["嘱", ["shoku"], []],
  ["織", ["shoku", "shiki"], ["o(ru)"]],
  ["職", ["shoku"], []],
  ["辱", ["joku"], ["hazukashi(meru)"]],
  ["尻", [], ["shiri"]],
  ["心", ["shin"], ["kokoro"]],
  ["申", ["shin"], ["moo(su)"]],
  ["伸", ["shin"], ["no(biru)", "no(basu)", "no(beru)"]],
  ["臣", ["shin", "jin"], []],
  ["芯", ["shin"], []],
  ["身", ["shin"], ["mi"]],
  ["辛", ["shin"], ["kara(i)"]],
  ["侵", ["shin"], ["oka(su)"]],
  ["信", ["shin"], []],
  ["津", ["shin"], ["tsu"]],
  ["神", ["shin", "jin"], ["kami", "[kan]", "[koo]"]],
  ["唇", ["shin"], ["kuchibiru"]],
  ["娠", ["shin"], []],
  ["振", ["shin"], ["fu(ru)", "fu(ruu)", "fu(reru)"]],
  ["浸", ["shin"], ["hita(su)", "hita(ru)"]],
  ["真", ["shin"], ["ma"]],
  ["針", ["shin"], ["hari"]],
  ["深", ["shin"], ["fuka(i)", "fuka(maru)", "fuka(meru)"]],
  ["紳", ["shin"], []],
  ["進", ["shin"], ["susu(mu)", "susu(meru)"]],
  ["森", ["shin"], ["mori"]],
  ["診", ["shin"], ["mi(ru)"]],
  ["寝", ["shin"], ["ne(ru)", "ne(kasu)"]],
  ["慎", ["shin"], ["tsutsushi(mu)"]],
  ["新", ["shin"], ["atara(shii)", "ara(ta)", "nii"]],
  ["審", ["shin"], []],
  ["震", ["shin"], ["furu(u)", "furu(eru)"]],
  ["薪", ["shin"], ["takigi"]],
  ["親", ["shin"], ["oya", "shita(shii)", "shita(shimu)"]],
  ["人", ["jin", "nin"], ["hito"]],
  ["刃", ["jin"], ["ha"]],
  ["仁", ["jin", "[ni]"], []],
  ["尽", ["jin"], ["tsu(kusu)", "tsu(kiru)", "tsu(kasu)"]],
  ["迅", ["jin"], []],
  ["甚", ["jin"], ["hanaha(da)", "hanaha(dashii)"]],
  ["陣", ["jin"], []],
  ["尋", ["jin"], ["tazu(neru)"]],
  ["腎", ["jin"], []],
  ["須", ["su"], []],
  ["図", ["zu", "to"], ["haka(ru)"]],
  ["水", ["sui"], ["mizu"]],
  ["吹", ["sui"], ["fu(ku)"]],
  ["垂", ["sui"], ["ta(reru)", "ta(rasu)"]],
  ["炊", ["sui"], ["ta(ku)"]],
  ["帥", ["sui"], []],
  ["粋", ["sui"], ["iki"]],
  ["衰", ["sui"], ["otoro(eru)"]],
  ["推", ["sui"], ["o(su)"]],
  ["酔", ["sui"], ["yo(u)"]],
  ["遂", ["sui"], ["to(geru)"]],
  ["睡", ["sui"], []],
  ["穂", ["sui"], ["ho"]],
  ["随", ["zui"], []],
  ["髄", ["zui"], []],
  ["枢", ["suu"], []],
  ["崇", ["suu"], []],
  ["数", ["suu", "[su]"], ["kazu", "kazo(eru)"]],
  ["据", [], ["su(eru)", "su(waru)"]],
  ["杉", [], ["sugi"]],
  ["裾", [], ["suso"]],
  ["寸", ["sun"], []],
  ["瀬", [], ["se"]],
  ["是", ["ze"], []],
  ["井", ["sei", "[shoo]"], ["i"]],
  ["世", ["sei", "se"], ["yo"]],
  ["正", ["sei", "shoo"], ["tada(shii)", "tada(su)", "masa"]],
  [
    "生",
    ["sei", "shoo"],
    [
      "i(kiru)",
      "i(kasu)",
      "i(keru)",
      "u(mareru)",
      "u(mu)",
      "o(u)",
      "ha(eru)",
      "ha(yasu)",
      "ki",
      "nama",
    ],
  ],
  ["成", ["sei", "[joo]"], ["na(ru)", "na(su)"]],
  ["西", ["sei", "sai"], ["nishi"]],
  ["声", ["sei", "[shoo]"], ["koe", "[kowa]"]],
  ["制", ["sei"], []],
  ["姓", ["sei", "shoo"], []],
  ["征", ["sei"], []],
  ["性", ["sei", "shoo"], []],
  ["青", ["sei", "[shoo]"], ["ao", "ao(i)"]],
  ["斉", ["sei"], []],
  ["政", ["sei", "[shoo]"], ["matsurigoto"]],
  ["星", ["sei", "[shoo]"], ["hoshi"]],
  ["牲", ["sei"], []],
  ["省", ["sei", "shoo"], ["kaeri(miru)", "habu(ku)"]],
  ["凄", ["sei"], []],
  ["逝", ["sei"], ["yu(ku)", "i(ku)"]],
  ["清", ["sei", "[shoo]"], ["kiyo(i)", "kiyo(maru)", "kiyo(meru)"]],
  ["盛", ["sei", "[joo]"], ["mo(ru)", "saka(ru)", "saka(n)"]],
  ["婿", ["sei"], ["muko"]],
  ["晴", ["sei"], ["ha(reru)", "ha(rasu)"]],
  ["勢", ["sei"], ["ikio(i)"]],
  ["聖", ["sei"], []],
  ["誠", ["sei"], ["makoto"]],
  ["精", ["sei", "[shoo]"], []],
  ["製", ["sei"], []],
  ["誓", ["sei"], ["chika(u)"]],
  [
    "静",
    ["sei", "[joo]"],
    ["shizu", "shizu(ka)", "shizu(maru)", "shizu(meru)"],
  ],
  ["請", ["sei", "[shin]"], ["ko(u)", "u(keru)"]],
  ["整", ["sei"], ["totono(eru)", "totono(u)"]],
  ["醒", ["sei"], []],
  ["税", ["zei"], []],
  ["夕", ["seki"], ["yuu"]],
  ["斥", ["seki"], []],
  ["石", ["seki", "[shaku]", "[koku]"], ["ishi"]],
  ["赤", ["seki", "[shaku]"], ["aka", "aka(i)", "aka(ramu)", "aka(rameru)"]],
  ["昔", ["seki", "[shaku]"], ["mukashi"]],
  ["析", ["seki"], []],
  ["席", ["seki"], []],
  ["脊", ["seki"], []],
  ["隻", ["seki"], []],
  ["惜", ["seki"], ["o(shii)", "o(shimu)"]],
  ["戚", ["seki"], []],
  ["責", ["seki"], ["se(meru)"]],
  ["跡", ["seki"], ["ato"]],
  ["積", ["seki"], ["tsu(mu)", "tsu(moru)"]],
  ["績", ["seki"], []],
  ["籍", ["seki"], []],
  ["切", ["setsu", "[sai]"], ["ki(ru)", "ki(reru)"]],
  ["折", ["setsu"], ["o(ru)", "ori", "o(reru)"]],
  ["拙", ["setsu"], ["tsutana(i)"]],
  ["窃", ["setsu"], []],
  ["接", ["setsu"], ["tsu(gu)"]],
  ["設", ["setsu"], ["moo(keru)"]],
  ["雪", ["setsu"], ["yuki"]],
  ["摂", ["setsu"], []],
  ["節", ["setsu", "[sechi]"], ["fushi"]],
  ["説", ["setsu", "[zei]"], ["to(ku)"]],
  ["舌", ["zetsu"], ["shita"]],
  ["絶", ["zetsu"], ["ta(eru)", "ta(yasu)", "ta(tsu)"]],
  ["千", ["sen"], ["chi"]],
  ["川", ["sen"], ["kawa"]],
  ["仙", ["sen"], []],
  ["占", ["sen"], ["shi(meru)", "urana(u)"]],
  ["先", ["sen"], ["saki"]],
  ["宣", ["sen"], []],
  ["専", ["sen"], ["moppa(ra)"]],
  ["泉", ["sen"], ["izumi"]],
  ["浅", ["sen"], ["asa(i)"]],
  ["洗", ["sen"], ["ara(u)"]],
  ["染", ["sen"], ["so(meru)", "so(maru)", "shi(miru)", "shi(mi)"]],
  ["扇", ["sen"], ["oogi"]],
  ["栓", ["sen"], []],
  ["旋", ["sen"], []],
  ["船", ["sen"], ["fune", "[funa]"]],
  ["戦", ["sen"], ["ikusa", "tataka(u)"]],
  ["煎", ["sen"], ["i(ru)"]],
  ["羨", ["sen"], ["uraya(mu)", "uraya(mashii)"]],
  ["腺", ["sen"], []],
  ["詮", ["sen"], []],
  ["践", ["sen"], []],
  ["箋", ["sen"], []],
  ["銭", ["sen"], ["zeni"]],
  ["潜", ["sen"], ["hiso(mu)", "mogu(ru)"]],
  ["線", ["sen"], []],
  ["遷", ["sen"], []],
  ["選", ["sen"], ["era(bu)"]],
  ["薦", ["sen"], ["susu(meru)"]],
  ["繊", ["sen"], []],
  ["鮮", ["sen"], ["aza(yaka)"]],
  ["全", ["zen"], ["matta(ku)", "sube(te)"]],
  ["前", ["zen"], ["mae"]],
  ["善", ["zen"], ["yo(i)"]],
  ["然", ["zen", "nen"], []],
  ["禅", ["zen"], []],
  ["漸", ["zen"], []],
  ["膳", ["zen"], []],
  ["繕", ["zen"], ["tsukuro(u)"]],
  ["狙", ["so"], ["nera(u)"]],
  ["阻", ["so"], ["haba(mu)"]],
  ["祖", ["so"], []],
  ["租", ["so"], []],
  ["素", ["so", "su"], []],
  ["措", ["so"], []],
  ["粗", ["so"], ["ara(i)"]],
  ["組", ["so"], ["ku(mu)", "kumi"]],
  ["疎", ["so"], ["uto(i)", "uto(mu)"]],
  ["訴", ["so"], ["utta(eru)"]],
  ["塑", ["so"], []],
  ["遡", ["so"], ["sakanobo(ru)"]],
  ["礎", ["so"], ["ishizue"]],
  ["双", ["soo"], ["futa"]],
  ["壮", ["soo"], []],
  ["早", ["soo", "[saQ]"], ["haya(i)", "haya(maru)", "haya(meru)"]],
  ["争", ["soo"], ["araso(u)"]],
  ["走", ["soo"], ["hashi(ru)"]],
  ["奏", ["soo"], ["kana(deru)"]],
  ["相", ["soo", "shoo"], ["ai"]],
  ["荘", ["soo"], []],
  ["草", ["soo"], ["kusa"]],
  ["送", ["soo"], ["oku(ru)"]],
  ["倉", ["soo"], ["kura"]],
  ["捜", ["soo"], ["saga(su)"]],
  ["挿", ["soo"], ["sa(su)"]],
  ["桑", ["soo"], ["kuwa"]],
  ["巣", ["soo"], ["su"]],
  ["掃", ["soo"], ["ha(ku)"]],
  ["曹", ["soo"], []],
  ["曽", ["soo", "[zo]"], []],
  ["爽", ["soo"], ["sawa(yaka)"]],
  ["窓", ["soo"], ["mado"]],
  ["創", ["soo"], ["tsuku(ru)"]],
  ["喪", ["soo"], ["mo"]],
  ["痩", ["soo"], ["ya(seru)"]],
  ["葬", ["soo"], ["hoomu(ru)"]],
  ["装", ["soo", "shoo"], ["yosoo(u)"]],
  ["僧", ["soo"], []],
  ["想", ["soo", "[so]"], []],
  ["層", ["soo"], []],
  ["総", ["soo"], []],
  ["遭", ["soo"], ["a(u)"]],
  ["槽", ["soo"], []],
  ["踪", ["soo"], []],
  ["操", ["soo"], ["misao", "ayatsu(ru)"]],
  ["燥", ["soo"], []],
  ["霜", ["soo"], ["shimo"]],
  ["騒", ["soo"], ["sawa(gu)"]],
  ["藻", ["soo"], ["mo"]],
  ["造", ["zoo"], ["tsuku(ru)"]],
  ["像", ["zoo"], []],
  ["増", ["zoo"], ["ma(su)", "fu(eru)", "fu(yasu)"]],
  ["憎", ["zoo"], ["niku(mu)", "niku(i)", "niku(rashii)", "niku(shimi)"]],
  ["蔵", ["zoo"], ["kura"]],
  ["贈", ["zoo", "[soo]"], ["oku(ru)"]],
  ["臓", ["zoo"], []],
  ["即", ["soku"], []],
  ["束", ["soku"], ["taba"]],
  ["足", ["soku"], ["ashi", "ta(riru)", "ta(ru)", "ta(su)"]],
  ["促", ["soku"], ["unaga(su)"]],
  ["則", ["soku"], []],
  ["息", ["soku"], ["iki"]],
  ["捉", ["soku"], ["tora(eru)"]],
  ["速", ["soku"], ["haya(i)", "haya(meru)", "haya(maru)", "sumi(yaka)"]],
  ["側", ["soku"], ["gawa"]],
  ["測", ["soku"], ["haka(ru)"]],
  ["俗", ["zoku"], []],
  ["族", ["zoku"], []],
  ["属", ["zoku"], []],
  ["賊", ["zoku"], []],
  ["続", ["zoku"], ["tsuzu(ku)", "tsuzu(keru)"]],
  ["卒", ["sotsu"], []],
  ["率", ["sotsu", "ritsu"], ["hiki(iru)"]],
  ["存", ["son", "zon"], []],
  ["村", ["son"], ["mura"]],
  ["孫", ["son"], ["mago"]],
  ["尊", ["son"], ["tatto(i)", "tooto(i)", "tatto(bu)", "tooto(bu)"]],
  ["損", ["son"], ["soko(nau)", "soko(neru)"]],
  ["遜", ["son"], []],
  ["他", ["ta"], ["hoka"]],
  ["多", ["ta"], ["oo(i)"]],
  ["汰", ["ta"], []],
  ["打", ["da"], ["u(tsu)"]],
  ["妥", ["da"], []],
  ["唾", ["da"], ["tsuba"]],
  ["堕", ["da"], []],
  ["惰", ["da"], []],
  ["駄", ["da"], []],
  ["太", ["tai", "ta"], ["futo(i)", "futo(ru)"]],
  ["対", ["tai", "tsui"], []],
  ["体", ["tai", "tei"], ["karada"]],
  ["耐", ["tai"], ["ta(eru)"]],
  ["待", ["tai"], ["ma(tsu)"]],
  ["怠", ["tai"], ["okota(ru)", "nama(keru)"]],
  ["胎", ["tai"], []],
  ["退", ["tai"], ["shirizo(ku)", "shirizo(keru)"]],
  ["帯", ["tai"], ["o(biru)", "obi"]],
  ["泰", ["tai"], []],
  ["堆", ["tai"], []],
  ["袋", ["tai"], ["fukuro"]],
  ["逮", ["tai"], []],
  ["替", ["tai"], ["ka(eru)", "ka(waru)"]],
  ["貸", ["tai"], ["ka(su)"]],
  ["隊", ["tai"], []],
  ["滞", ["tai"], ["todokoo(ru)"]],
  ["態", ["tai"], []],
  ["戴", ["tai"], []],
  ["大", ["dai", "tai"], ["oo", "oo(kii)", "oo(ini)"]],
  ["代", ["dai", "tai"], ["ka(waru)", "ka(eru)", "yo", "shiro"]],
  ["台", ["dai", "tai"], []],
  ["第", ["dai"], []],
  ["題", ["dai"], []],
  ["滝", [], ["taki"]],
  ["宅", ["taku"], []],
  ["択", ["taku"], []],
  ["沢", ["taku"], ["sawa"]],
  ["卓", ["taku"], []],
  ["拓", ["taku"], []],
  ["託", ["taku"], []],
  ["濯", ["taku"], []],
  ["諾", ["daku"], []],
  ["濁", ["daku"], ["nigo(ru)", "nigo(su)"]],
  ["但", [], ["tada(shi)"]],
  ["達", ["tatsu"], []],
  ["脱", ["datsu"], ["nu(gu)", "nu(geru)"]],
  ["奪", ["datsu"], ["uba(u)"]],
  ["棚", [], ["tana"]],
  ["誰", [], ["dare"]],
  ["丹", ["tan"], []],
  ["旦", ["tan", "dan"], []],
  ["担", ["tan"], ["katsu(gu)", "nina(u)"]],
  ["単", ["tan"], []],
  ["炭", ["tan"], ["sumi"]],
  ["胆", ["tan"], []],
  ["探", ["tan"], ["sagu(ru)", "saga(su)"]],
  ["淡", ["tan"], ["awa(i)"]],
  ["短", ["tan"], ["mijika(i)"]],
  ["嘆", ["tan"], ["nage(ku)", "nage(kawashii)"]],
  ["端", ["tan"], ["hashi", "ha", "hata"]],
  ["綻", ["tan"], ["hokoro(biru)"]],
  ["誕", ["tan"], []],
  ["鍛", ["tan"], ["kita(eru)"]],
  ["団", ["dan", "[ton]"], []],
  ["男", ["dan", "nan"], ["otoko"]],
  ["段", ["dan"], []],
  ["断", ["dan"], ["ta(tsu)", "kotowa(ru)"]],
  ["弾", ["dan"], ["hi(ku)", "hazu(mu)", "tama"]],
  ["暖", ["dan"], ["atata(ka)", "atata(kai)", "atata(maru)", "atata(meru)"]],
  ["談", ["dan"], []],
  ["壇", ["dan", "[tan]"], []],
  ["地", ["chi", "ji"], []],
  ["池", ["chi"], ["ike"]],
  ["知", ["chi"], ["shi(ru)"]],
  ["値", ["chi"], ["ne", "atai"]],
  ["恥", ["chi"], ["ha(jiru)", "haji", "ha(jirau)", "ha(zukashii)"]],
  ["致", ["chi"], ["ita(su)"]],
  ["遅", ["chi"], ["oku(reru)", "oku(rasu)", "oso(i)"]],
  ["痴", ["chi"], []],
  ["稚", ["chi"], []],
  ["置", ["chi"], ["o(ku)"]],
  ["緻", ["chi"], []],
  ["竹", ["chiku"], ["take"]],
  ["畜", ["chiku"], []],
  ["逐", ["chiku"], []],
  ["蓄", ["chiku"], ["takuwa(eru)"]],
  ["築", ["chiku"], ["kizu(ku)"]],
  ["秩", ["chitsu"], []],
  ["窒", ["chitsu"], []],
  ["茶", ["cha", "sa"], []],
  ["着", ["chaku", "[jaku]"], ["ki(ru)", "ki(seru)", "tsu(ku)", "tsu(keru)"]],
  ["嫡", ["chaku"], []],
  ["中", ["chuu", "[jyuu]"], ["naka"]],
  ["仲", ["chuu"], ["naka"]],
  ["虫", ["chuu"], ["mushi"]],
  ["沖", ["chuu"], ["oki"]],
  ["宙", ["chuu"], []],
  ["忠", ["chuu"], []],
  ["抽", ["chuu"], []],
  ["注", ["chuu"], ["soso(gu)"]],
  ["昼", ["chuu"], ["hiru"]],
  ["柱", ["chuu"], ["hashira"]],
  ["衷", ["chuu"], []],
  ["酎", ["chuu"], []],
  ["鋳", ["chuu"], ["i(ru)"]],
  ["駐", ["chuu"], []],
  ["著", ["cho"], ["arawa(su)", "ichijiru(shii)"]],
  ["貯", ["cho"], []],
  ["丁", ["tei", "choo"], []],
  ["弔", ["choo"], ["tomura(u)"]],
  ["庁", ["choo"], []],
  ["兆", ["choo"], ["kiza(su)", "kiza(shi)"]],
  ["町", ["choo"], ["machi"]],
  ["長", ["choo"], ["naga(i)"]],
  ["挑", ["choo"], ["ido(mu)"]],
  ["帳", ["choo"], []],
  ["張", ["choo"], ["ha(ru)"]],
  ["彫", ["choo"], ["ho(ru)"]],
  ["眺", ["choo"], ["naga(meru)"]],
  ["釣", ["choo"], ["tsu(ru)"]],
  ["頂", ["choo"], ["itada(ku)", "itadaki"]],
  ["鳥", ["choo"], ["tori"]],
  ["朝", ["choo"], ["asa"]],
  ["貼", ["choo"], ["ha(ru)"]],
  ["超", ["choo"], ["ko(eru)", "ko(su)"]],
  ["腸", ["choo"], []],
  ["跳", ["choo"], ["ha(neru)", "to(bu)"]],
  ["徴", ["choo"], []],
  ["嘲", ["choo"], ["azake(ru)"]],
  ["潮", ["choo"], ["shio"]],
  ["澄", ["choo"], ["su(mu)", "su(masu)"]],
  ["調", ["choo"], ["shira(beru)", "totono(u)", "totono(eru)"]],
  ["聴", ["choo"], ["ki(ku)"]],
  ["懲", ["choo"], ["ko(riru)", "ko(rasu)", "ko(rashimeru)"]],
  ["直", ["choku", "jiki"], ["tada(chini)", "nao(su)", "nao(ru)"]],
  ["勅", ["choku"], []],
  ["捗", ["choku"], []],
  ["沈", ["chin"], ["shizu(mu)", "shizu(meru)"]],
  ["珍", ["chin"], ["mezura(shii)"]],
  ["朕", ["chin"], []],
  ["陳", ["chin"], []],
  ["賃", ["chin"], []],
  ["鎮", ["chin"], ["shizu(meru)", "shizu(maru)"]],
  ["追", ["tsui"], ["o(u)"]],
  ["椎", ["tsui"], []],
  ["墜", ["tsui"], []],
  ["通", ["tsuu", "[tsu]"], ["too(ru)", "too(su)", "kayo(u)"]],
  ["痛", ["tsuu"], ["ita(i)", "ita(mu)", "ita(meru)"]],
  ["塚", [], ["tsuka"]],
  ["漬", [], ["tsu(keru)", "tsu(karu)"]],
  ["坪", [], ["tsubo"]],
  ["爪", [], ["tsume", "[tsuma]"]],
  ["鶴", ["tsuru"], []],
  ["低", ["tei"], ["hiku(i)", "hiku(meru)", "hiku(maru)"]],
  ["呈", ["tei"], []],
  ["廷", ["tei"], []],
  ["弟", ["tei", "[dai]", "[de]"], ["otooto"]],
  ["定", ["tei", "joo"], ["sada(meru)", "sada(maru)", "sada(ka)"]],
  ["底", ["tei"], ["soko"]],
  ["抵", ["tei"], []],
  ["邸", ["tei"], []],
  ["亭", ["tei"], []],
  ["貞", ["tei"], []],
  ["帝", ["tei"], []],
  ["訂", ["tei"], []],
  ["庭", ["tei"], ["niwa"]],
  ["逓", ["tei"], []],
  ["停", ["tei"], []],
  ["偵", ["tei"], []],
  ["堤", ["tei"], ["tsutsumi"]],
  ["提", ["tei"], ["sa(geru)"]],
  ["程", ["tei"], ["hodo"]],
  ["艇", ["tei"], []],
  ["締", ["tei"], ["shi(maru)", "shi(meru)"]],
  ["諦", ["tei"], ["akira(meru)"]],
  ["泥", ["dei"], ["doro"]],
  ["的", ["teki"], ["mato"]],
  ["笛", ["teki"], ["fue"]],
  ["摘", ["teki"], ["tsu(mu)"]],
  ["滴", ["teki"], ["shizuku", "shitata(ru)"]],
  ["適", ["teki"], []],
  ["敵", ["teki"], ["kataki"]],
  ["溺", ["deki"], ["obo(reru)"]],
  ["迭", ["tetsu"], []],
  ["哲", ["tetsu"], []],
  ["鉄", ["tetsu"], []],
  ["徹", ["tetsu"], []],
  ["撤", ["tetsu"], []],
  ["天", ["ten"], ["ame", "[ama]"]],
  ["典", ["ten"], []],
  ["店", ["ten"], ["mise"]],
  ["点", ["ten"], []],
  ["展", ["ten"], []],
  ["添", ["ten"], ["so(eru)", "so(u)"]],
  ["転", ["ten"], ["koro(garu)", "koro(geru)", "koro(gasu)", "koro(bu)"]],
  ["填", ["ten"], []],
  ["田", ["den"], ["ta"]],
  ["伝", ["den"], ["tsuta(waru)", "tsuta(eru)", "tsuta(u)"]],
  ["殿", ["den", "ten"], ["tono", "dono"]],
  ["電", ["den"], []],
  ["斗", ["to"], []],
  ["吐", ["to"], ["ha(ku)"]],
  ["妬", ["to"], ["neta(mu)"]],
  ["徒", ["to"], []],
  ["途", ["to"], []],
  ["都", ["to", "tsu"], ["miyako"]],
  ["渡", ["to"], ["wata(ru)", "wata(su)"]],
  ["塗", ["to"], ["nu(ru)"]],
  ["賭", ["to"], ["ka(keru)"]],
  ["土", ["do", "to"], ["tsuchi"]],
  ["奴", ["do"], []],
  ["努", ["do"], ["tsuto(meru)"]],
  ["度", ["do", "[to]", "[taku]"], ["tabi"]],
  ["怒", ["do"], ["ika(ru)", "oko(ru)"]],
  ["刀", ["too"], ["katana"]],
  ["冬", ["too"], ["fuyu"]],
  ["灯", ["too"], ["hi"]],
  ["当", ["too"], ["a(taru)", "a(teru)"]],
  ["投", ["too"], ["na(geru)"]],
  ["豆", ["too", "[zu]"], ["mame"]],
  ["東", ["too"], ["higashi"]],
  ["到", ["too"], []],
  ["逃", ["too"], ["ni(geru)", "ni(gasu)", "noga(su)", "noga(reru)"]],
  ["倒", ["too"], ["tao(reru)", "tao(su)"]],
  ["凍", ["too"], ["koo(ru)", "kogo(eru)"]],
  ["唐", ["too"], ["kara"]],
  ["島", ["too"], ["shima"]],
  ["桃", ["too"], ["momo"]],
  ["討", ["too"], ["u(tsu)"]],
  ["透", ["too"], ["su(ku)", "su(kasu)", "su(keru)"]],
  ["党", ["too"], []],
  ["悼", ["too"], ["ita(mu)"]],
  ["盗", ["too"], ["nusu(mu)"]],
  ["陶", ["too"], []],
  ["塔", ["too"], []],
  ["搭", ["too"], []],
  ["棟", ["too"], ["mune", "[muna]"]],
  ["湯", ["too"], ["yu"]],
  ["痘", ["too"], []],
  ["登", ["too", "to"], ["nobo(ru)"]],
  ["答", ["too"], ["kota(eru)", "kota(e)"]],
  ["等", ["too"], ["hito(shii)"]],
  ["筒", ["too"], ["tsutsu"]],
  ["統", ["too"], ["su(beru)"]],
  ["稲", ["too"], ["ine", "[ina]"]],
  ["踏", ["too"], ["fu(mu)", "fu(maeru)"]],
  ["糖", ["too"], []],
  ["頭", ["too", "zu", "[to]"], ["atama", "kashira"]],
  ["謄", ["too"], []],
  ["藤", ["too"], ["fuji"]],
  ["闘", ["too"], ["tataka(u)"]],
  ["騰", ["too"], []],
  ["同", ["doo"], ["ona(ji)"]],
  ["洞", ["doo"], ["hora"]],
  ["胴", ["doo"], []],
  ["動", ["doo"], ["ugo(ku)", "ugo(kasu)"]],
  ["堂", ["doo"], []],
  ["童", ["doo"], ["warabe"]],
  ["道", ["doo", "[too]"], ["michi"]],
  ["働", ["doo"], ["hatara(ku)"]],
  ["銅", ["doo"], []],
  ["導", ["doo"], ["michibi(ku)"]],
  ["瞳", ["doo"], ["hitomi"]],
  ["峠", [], ["tooge"]],
  ["匿", ["toku"], []],
  ["特", ["toku"], []],
  ["得", ["toku"], ["e(ru)", "u(ru)"]],
  ["督", ["toku"], []],
  ["徳", ["toku"], []],
  ["篤", ["toku"], []],
  ["毒", ["doku"], []],
  ["独", ["doku"], ["hito(ri)"]],
  ["読", ["doku", "toku", "[too]"], ["yo(mu)"]],
  ["栃", [], ["[tochi]"]],
  ["凸", ["totsu"], []],
  ["突", ["totsu"], ["tsu(ku)"]],
  ["届", [], ["todo(keru)", "todo(ku)"]],
  ["屯", ["ton"], []],
  ["豚", ["ton"], ["buta"]],
  ["頓", ["ton"], []],
  ["貪", ["don"], ["musabo(ru)"]],
  ["鈍", ["don"], ["nibu(i)", "nibu(ru)"]],
  ["曇", ["don"], ["kumo(ru)"]],
  ["丼", [], ["donburi", "[don]"]],
  ["那", ["na"], []],
  ["奈", ["na"], []],
  ["内", ["nai", "[dai]"], ["uchi"]],
  ["梨", [], ["nashi"]],
  ["謎", [], ["nazo"]],
  ["鍋", [], ["nabe"]],
  ["南", ["nan", "[na]"], ["minami"]],
  ["軟", ["nan"], ["yawa(raka)", "yawa(rakai)"]],
  ["難", ["nan"], ["kata(i)", "muzuka(shii)"]],
  ["二", ["ni"], ["futa", "futa(tsu)"]],
  ["尼", ["ni"], ["ama"]],
  ["弐", ["ni"], []],
  ["匂", [], ["nio(u)"]],
  ["肉", ["niku"], []],
  ["虹", [], ["niji"]],
  ["日", ["nichi", "jitsu"], ["hi", "ka"]],
  ["入", ["nyuu"], ["i(ru)", "i(reru)", "hai(ru)"]],
  ["乳", ["nyuu"], ["chichi", "chi"]],
  ["尿", ["nyoo"], []],
  ["任", ["nin"], ["maka(seru)", "maka(su)"]],
  ["妊", ["nin"], []],
  ["忍", ["nin"], ["shino(bu)", "shino(baseru)"]],
  ["認", ["nin"], ["mito(meru)"]],
  ["寧", ["nei"], []],
  ["熱", ["netsu"], ["atsu(i)"]],
  ["年", ["nen"], ["toshi"]],
  ["念", ["nen"], []],
  ["捻", ["nen"], []],
  ["粘", ["nen"], ["neba(ru)"]],
  ["燃", ["nen"], ["mo(eru)", "mo(yasu)", "mo(su)"]],
  ["悩", ["noo"], ["naya(mu)", "naya(masu)"]],
  [
    "納",
    ["noo", "[naQ]", "[na]", "[nan]", "[too]"],
    ["osa(meru)", "osa(maru)"],
  ],
  ["能", ["noo"], []],
  ["脳", ["noo"], []],
  ["農", ["noo"], []],
  ["濃", ["noo"], ["ko(i)"]],
  ["把", ["ha"], []],
  ["波", ["ha"], ["nami"]],
  ["派", ["ha"], []],
  ["破", ["ha"], ["yabu(ru)", "yabu(reru)"]],
  ["覇", ["ha"], []],
  ["馬", ["ba"], ["uma", "[ma]"]],
  ["婆", ["ba"], []],
  ["罵", ["ba"], ["nonoshi(ru)"]],
  ["拝", ["hai"], ["oga(mu)"]],
  ["杯", ["hai"], ["sakazuki"]],
  ["背", ["hai"], ["se", "sei", "somu(ku)", "somu(keru)"]],
  ["肺", ["hai"], []],
  ["俳", ["hai"], []],
  ["配", ["hai"], ["kuba(ru)"]],
  ["排", ["hai"], []],
  ["敗", ["hai"], ["yabu(reru)"]],
  ["廃", ["hai"], ["suta(reru)", "suta(ru)"]],
  ["輩", ["hai"], []],
  ["売", ["bai"], ["u(ru)", "u(reru)"]],
  ["倍", ["bai"], []],
  ["梅", ["bai"], ["ume"]],
  ["培", ["bai"], ["tsuchika(u)"]],
  ["陪", ["bai"], []],
  ["媒", ["bai"], []],
  ["買", ["bai"], ["ka(u)"]],
  ["賠", ["bai"], []],
  ["白", ["haku", "byaku"], ["shiro", "[shira]", "shiro(i)"]],
  ["伯", ["haku"], []],
  ["拍", ["haku", "[hyoo]"], []],
  ["泊", ["haku"], ["to(maru)", "to(meru)"]],
  ["迫", ["haku"], ["sema(ru)"]],
  ["剥", ["haku"], ["ha(gasu)", "ha(gu)", "ha(gareru)", "ha(geru)"]],
  ["舶", ["haku"], []],
  ["博", ["haku", "[baku]"], []],
  [
    "薄",
    ["haku"],
    ["usu(i)", "usu(meru)", "usu(maru)", "usu(ragu)", "usu(reru)"],
  ],
  ["麦", ["baku"], ["mugi"]],
  ["漠", ["baku"], []],
  ["縛", ["baku"], ["shiba(ru)"]],
  ["爆", ["baku"], []],
  ["箱", [], ["hako"]],
  ["箸", [], ["hashi"]],
  ["畑", [], ["hata", "hatake"]],
  ["肌", [], ["hada"]],
  ["八", ["hachi"], ["ya", "ya(tsu)", "yat(tsu)", "[yoo]"]],
  ["鉢", ["[hatsu]", "hachi"], []],
  ["発", ["hatsu", "hotsu"], []],
  ["髪", ["hatsu"], ["kami"]],
  ["伐", ["batsu"], []],
  ["抜", ["batsu"], ["nu(ku)", "nu(keru)", "nu(kasu)", "nu(karu)"]],
  ["罰", ["batsu", "bachi"], []],
  ["閥", ["batsu"], []],
  ["反", ["han", "[hon]", "[tan]"], ["so(ru)", "so(rasu)"]],
  ["半", ["han"], ["naka(ba)"]],
  ["氾", ["han"], []],
  ["犯", ["han"], ["oka(su)"]],
  ["帆", ["han"], ["ho"]],
  ["汎", ["han"], []],
  ["伴", ["han", "ban"], ["tomona(u)"]],
  ["判", ["han", "ban"], []],
  ["坂", ["han"], ["saka"]],
  ["阪", ["han"], []],
  ["板", ["han", "ban"], ["ita"]],
  ["版", ["han"], []],
  ["班", ["han"], []],
  ["畔", ["han"], []],
  ["般", ["han"], []],
  ["販", ["han"], []],
  ["斑", ["han"], []],
  ["飯", ["han"], ["meshi"]],
  ["搬", ["han"], []],
  ["煩", ["han", "[bon]"], ["wazura(u)", "wazura(wasu)"]],
  ["頒", ["han"], []],
  ["範", ["han"], []],
  ["繁", ["han"], []],
  ["藩", ["han"], []],
  ["晩", ["ban"], []],
  ["番", ["ban"], []],
  ["蛮", ["ban"], []],
  ["盤", ["ban"], []],
  ["比", ["hi"], ["kura(beru)"]],
  ["皮", ["hi"], ["kawa"]],
  ["妃", ["hi"], []],
  ["否", ["hi"], ["ina"]],
  ["批", ["hi"], []],
  ["彼", ["hi"], ["kare", "[kano]"]],
  ["披", ["hi"], []],
  ["肥", ["hi"], ["ko(eru)", "koe", "ko(yasu)", "ko(yashi)"]],
  ["非", ["hi"], []],
  ["卑", ["hi"], ["iya(shii)", "iya(shimu)", "iya(shimeru)"]],
  ["飛", ["hi"], ["to(bu)", "to(basu)"]],
  ["疲", ["hi"], ["tsuka(reru)"]],
  ["秘", ["hi"], ["hi(meru)"]],
  ["被", ["hi"], ["koomu(ru)"]],
  ["悲", ["hi"], ["kana(shii)", "kana(shimu)"]],
  ["扉", ["hi"], ["tobira"]],
  ["費", ["hi"], ["tsui(yasu)", "tsui(eru)"]],
  ["碑", ["hi"], []],
  ["罷", ["hi"], []],
  ["避", ["hi"], ["sa(keru)"]],
  ["尾", ["bi"], ["o"]],
  ["眉", ["bi", "[mi]"], ["mayu"]],
  ["美", ["bi"], ["utsuku(shii)"]],
  ["備", ["bi"], ["sona(eru)", "sona(waru)"]],
  ["微", ["bi"], []],
  ["鼻", ["bi"], ["hana"]],
  ["膝", [], ["hiza"]],
  ["肘", [], ["hiji"]],
  ["匹", ["hitsu"], ["hiki"]],
  ["必", ["hitsu"], ["kanara(zu)"]],
  ["泌", ["hitsu", "hi"], []],
  ["筆", ["hitsu"], ["fude"]],
  ["姫", [], ["hime"]],
  ["百", ["hyaku"], []],
  ["氷", ["hyoo"], ["koori", "hi"]],
  ["表", ["hyoo"], ["omote", "arawa(su)", "arawa(reru)"]],
  ["俵", ["hyoo"], ["tawara"]],
  ["票", ["hyoo"], []],
  ["評", ["hyoo"], []],
  ["漂", ["hyoo"], ["tadayo(u)"]],
  ["標", ["hyoo"], []],
  ["苗", ["byoo"], ["nae", "[nawa]"]],
  ["秒", ["byoo"], []],
  ["病", ["byoo", "[hei]"], ["ya(mu)", "yamai"]],
  ["描", ["byoo"], ["ega(ku)", "ka(ku)"]],
  ["猫", ["byoo"], ["neko"]],
  ["品", ["hin"], ["shina"]],
  ["浜", ["hin"], ["hama"]],
  ["貧", ["hin", "bin"], ["mazu(shii)"]],
  ["賓", ["hin"], []],
  ["頻", ["hin"], []],
  ["敏", ["bin"], []],
  ["瓶", ["bin"], []],
  ["不", ["fu", "bu"], []],
  ["夫", ["fu", "[fuu]"], ["otto"]],
  ["父", ["fu"], ["chichi"]],
  ["付", ["fu"], ["tsu(keru)", "tsu(ku)"]],
  ["布", ["fu"], ["nuno"]],
  ["扶", ["fu"], []],
  ["府", ["fu"], []],
  ["怖", ["fu"], ["kowa(i)"]],
  ["阜", ["[fu]"], []],
  ["附", ["fu"], []],
  ["訃", ["fu"], []],
  ["負", ["fu"], ["ma(keru)", "ma(kasu)", "o(u)"]],
  ["赴", ["fu"], ["omomu(ku)"]],
  ["浮", ["fu"], ["u(ku)", "u(kareru)", "u(kabu)", "u(kaberu)"]],
  ["婦", ["fu"], []],
  ["符", ["fu"], []],
  ["富", ["fu", "[fuu]"], ["to(mu)", "tomi"]],
  ["普", ["fu"], []],
  ["腐", ["fu"], ["kusa(ru)", "kusa(reru)", "kusa(rasu)"]],
  ["敷", ["fu"], ["shi(ku)"]],
  ["膚", ["fu"], []],
  ["賦", ["fu"], []],
  ["譜", ["fu"], []],
  ["侮", ["bu"], ["anado(ru)"]],
  ["武", ["bu", "mu"], []],
  ["部", ["bu"], []],
  ["舞", ["bu"], ["ma(u)", "mai"]],
  ["封", ["fuu", "hoo"], []],
  ["風", ["fuu", "[fu]"], ["kaze", "[kaza]"]],
  ["伏", ["fuku"], ["fu(seru)", "fu(su)"]],
  ["服", ["fuku"], []],
  ["副", ["fuku"], []],
  ["幅", ["fuku"], ["haba"]],
  ["復", ["fuku"], []],
  ["福", ["fuku"], []],
  ["腹", ["fuku"], ["hara"]],
  ["複", ["fuku"], []],
  ["覆", ["fuku"], ["oo(u)", "kutsugae(su)", "kutsugae(ru)"]],
  ["払", ["futsu"], ["hara(u)"]],
  ["沸", ["futsu"], ["wa(ku)", "wa(kasu)"]],
  ["仏", ["butsu"], ["hotoke"]],
  ["物", ["butsu", "motsu"], ["mono"]],
  ["粉", ["fun"], ["ko", "kona"]],
  [
    "紛",
    ["fun"],
    ["magi(reru)", "magi(rasu)", "magi(rawasu)", "magi(rawashii)"],
  ],
  ["雰", ["fun"], []],
  ["噴", ["fun"], ["fu(ku)"]],
  ["墳", ["fun"], []],
  ["憤", ["fun"], ["ikidoo(ru)"]],
  ["奮", ["fun"], ["furu(u)"]],
  [
    "分",
    ["bun", "fun", "bu"],
    ["wa(keru)", "wa(kareru)", "wa(karu)", "wa(katsu)"],
  ],
  ["文", ["bun", "mon"], ["fumi"]],
  ["聞", ["bun", "mon"], ["ki(ku)", "ki(koeru)"]],
  ["丙", ["hei"], []],
  ["平", ["hei", "byoo"], ["tai(ra)", "hira"]],
  ["兵", ["hei", "hyoo"], []],
  ["併", ["hei"], ["awa(seru)"]],
  ["並", ["hei"], ["nami", "mara(beru)", "nara(bu)", "nara(bini)"]],
  ["柄", ["hei"], ["gara", "e"]],
  ["陛", ["hei"], []],
  ["閉", ["hei"], ["to(jiru)", "to(zasu)", "shi(meru)", "shi(maru)"]],
  ["塀", ["hei"], []],
  ["幣", ["hei"], []],
  ["弊", ["hei"], []],
  ["蔽", ["hei"], []],
  ["餅", ["hei"], ["mochi"]],
  ["米", ["bei", "mai"], ["kome"]],
  ["壁", ["heki"], ["kabe"]],
  ["璧", ["heki"], []],
  ["癖", ["heki"], ["kuse"]],
  ["別", ["betsu"], ["waka(reru)"]],
  ["蔑", ["betsu"], ["sagesu(mu)"]],
  ["片", ["hen"], ["kata"]],
  ["辺", ["hen"], ["ata(ri)", "be"]],
  ["返", ["hen"], ["kae(su)", "kae(ru)"]],
  ["変", ["hen"], ["ka(waru)", "ka(eru)"]],
  ["偏", ["hen"], ["katayo(ru)"]],
  ["遍", ["hen"], []],
  ["編", ["hen"], ["a(mu)"]],
  ["弁", ["ben"], []],
  ["便", ["ben", "bin"], ["tayo(ri)"]],
  ["勉", ["ben"], []],
  ["歩", ["ho", "bu", "[fu]"], ["aru(ku)", "ayu(mu)"]],
  ["保", ["ho"], ["tamo(tsu)"]],
  ["哺", ["ho"], []],
  [
    "捕",
    ["ho"],
    ["to(raeru)", "to(rawareru)", "to(ru)", "tsuka(maeru)", "tsuka(maru)"],
  ],
  ["補", ["ho"], ["ogina(u)"]],
  ["舗", ["ho"], []],
  ["母", ["bo"], ["haha"]],
  ["募", ["bo"], ["tsuno(ru)"]],
  ["墓", ["bo"], ["haka"]],
  ["慕", ["bo"], ["shita(u)"]],
  ["暮", ["bo"], ["ku(reru)", "ku(rasu)"]],
  ["簿", ["bo"], []],
  ["方", ["hoo"], ["kata"]],
  ["包", ["hoo"], ["tsutsu(mu)"]],
  ["芳", ["hoo"], ["kanba(shii)"]],
  ["邦", ["hoo"], []],
  ["奉", ["hoo", "[bu]"], ["tatematsu(ru)"]],
  ["宝", ["hoo"], ["takara"]],
  ["抱", ["hoo"], ["da(ku)", "ida(ku)", "kaka(eru)"]],
  ["放", ["hoo"], ["hana(su)", "hana(tsu)", "hana(reru)", "hoo(ru)"]],
  ["法", ["hoo", "[haQ]", "[hoQ]"], []],
  ["泡", ["hoo"], ["awa"]],
  ["胞", ["hoo"], []],
  ["俸", ["hoo"], []],
  ["倣", ["hoo"], ["nara(u)"]],
  ["峰", ["hoo"], ["mine"]],
  ["砲", ["hoo"], []],
  ["崩", ["hoo"], ["kuzu(reru)", "kuzu(su)"]],
  ["訪", ["hoo"], ["otozu(reru)", "tazu(neru)"]],
  ["報", ["hoo"], ["muku(iru)"]],
  ["蜂", ["hoo"], ["hachi"]],
  ["豊", ["hoo"], ["yuta(ka)"]],
  ["飽", ["hoo"], ["a(kiru)", "a(kasu)"]],
  ["褒", ["hoo"], ["ho(meru)"]],
  ["縫", ["hoo"], ["nu(u)"]],
  ["亡", ["boo", "[moo]"], ["na(-i)"]],
  ["乏", ["boo"], ["tobo(shii)"]],
  ["忙", ["boo"], ["isoga(shii)"]],
  ["坊", ["boo", "[boQ]"], []],
  ["妨", ["boo"], ["samata(geru)"]],
  ["忘", ["boo"], ["wasu(reru)"]],
  ["防", ["boo"], ["fuse(gu)"]],
  ["房", ["boo"], ["fusa"]],
  ["肪", ["boo"], []],
  ["某", ["boo"], []],
  ["冒", ["boo"], ["oka(su)"]],
  ["剖", ["boo"], []],
  ["紡", ["boo"], ["tsumu(gu)"]],
  ["望", ["boo", "moo"], ["nozo(mu)"]],
  ["傍", ["boo"], ["katawa(ra)"]],
  ["帽", ["boo"], []],
  ["棒", ["boo"], []],
  ["貿", ["boo"], []],
  ["貌", ["boo"], []],
  ["暴", ["boo", "[baku]"], ["aba(ku)", "aba(reru)"]],
  ["膨", ["boo"], ["fuku(ramu)", "fuku(reru)"]],
  ["謀", ["boo", "[mu]"], ["haka(ru)"]],
  ["頬", ["hoo"], []],
  ["北", ["hoku"], ["kita"]],
  ["木", ["boku", "moku"], ["ki", "[ko]"]],
  ["朴", ["boku"], []],
  ["牧", ["boku"], ["maki"]],
  ["睦", ["boku"], []],
  ["僕", ["boku"], []],
  ["墨", ["boku"], ["sumi"]],
  ["撲", ["boku"], []],
  ["没", ["botsu"], []],
  ["勃", ["botsu"], []],
  ["堀", [], ["hori"]],
  ["本", ["hon"], ["moto"]],
  ["奔", ["hon"], []],
  ["翻", ["hon"], ["hirugae(ru)", "hirugae(su)"]],
  ["凡", ["bon", "[han]"], []],
  ["盆", ["bon"], []],
  ["麻", ["ma"], ["asa"]],
  ["摩", ["ma"], []],
  ["磨", ["ma"], ["miga(ku)"]],
  ["魔", ["ma"], []],
  ["毎", ["mai"], []],
  ["妹", ["mai"], ["imooto"]],
  ["枚", ["mai"], []],
  ["昧", ["mai"], []],
  ["埋", ["mai"], ["u(meru)", "u(maru)", "u(moreru)"]],
  ["幕", ["maku", "baku"], []],
  ["膜", ["maku"], []],
  ["枕", [], ["makura"]],
  ["又", [], ["mata"]],
  ["末", ["matsu", "batsu"], ["sue"]],
  ["抹", ["matsu"], []],
  ["万", ["man", "ban"], []],
  ["満", ["man"], ["mi(chiru)", "mi(tasu)"]],
  ["慢", ["man"], []],
  ["漫", ["man"], []],
  ["未", ["mi"], []],
  ["味", ["mi"], ["aji", "aji(wau)"]],
  ["魅", ["mi"], []],
  ["岬", [], ["misaki"]],
  ["密", ["mitsu"], []],
  ["蜜", ["mitsu"], []],
  ["脈", ["myaku"], []],
  ["妙", ["myoo"], []],
  ["民", ["min"], ["tami"]],
  ["眠", ["min"], ["nemu(ru)", "nemu(i)"]],
  ["矛", ["mu"], ["hoko"]],
  ["務", ["mu"], ["tsuto(meru)", "tsuto(maru)"]],
  ["無", ["mu", "bu"], ["na(i)"]],
  ["夢", ["mu"], ["yume"]],
  ["霧", ["mu"], ["kiri"]],
  ["娘", [], ["musume"]],
  ["名", ["mei", "myoo"], ["na"]],
  ["命", ["mei", "myoo"], ["inochi"]],
  [
    "明",
    ["mei", "myoo"],
    [
      "a(kari)",
      "aka(rui)",
      "aka(rumu)",
      "aka(ramu)",
      "aki(raka)",
      "a(keru)",
      "a(ku)",
      "a(kuru)",
      "a(kasu)",
    ],
  ],
  ["迷", ["mei"], ["mayo(u)"]],
  ["冥", ["mei", "myoo"], []],
  ["盟", ["mei"], []],
  ["銘", ["mei"], []],
  ["鳴", ["mei"], ["na(ku)", "na(ru)", "na(rasu)"]],
  ["滅", ["metsu"], ["horo(biru)", "horo(bosu)"]],
  ["免", ["men"], ["manuka(reru)"]],
  ["面", ["men"], ["omo", "omote", "tsura"]],
  ["綿", ["men"], ["wata"]],
  ["麺", ["men"], []],
  ["茂", ["mo"], ["shige(ru)"]],
  ["模", ["mo", "bo"], []],
  ["毛", ["moo"], ["ke"]],
  ["妄", ["moo", "boo"], []],
  ["盲", ["moo"], []],
  ["耗", ["moo", "[koo]"], []],
  ["猛", ["moo"], []],
  ["網", ["moo"], ["ami"]],
  ["目", ["moku", "[boku]"], ["me", "[ma]"]],
  ["黙", ["moku"], ["dama(ru)"]],
  ["門", ["mon"], ["kado"]],
  ["紋", ["mon"], []],
  ["問", ["mon"], ["to(u)", "to(i)", "[ton]"]],
  ["冶", ["ya"], []],
  ["夜", ["ya"], ["yo", "yoru"]],
  ["野", ["ya"], ["no"]],
  ["弥", [], ["ya"]],
  ["厄", ["yaku"], []],
  ["役", ["eki", "yaku"], []],
  ["約", ["yaku"], []],
  ["訳", ["yaku"], ["wake"]],
  ["薬", ["yaku"], ["kusuri"]],
  ["躍", ["yaku"], ["odo(ru)"]],
  ["闇", [], ["yami"]],
  ["由", ["yu", "yuu", "[yui]"], ["yoshi"]],
  ["油", ["yu"], ["abura"]],
  ["喩", ["yu"], []],
  ["愉", ["yu"], []],
  ["諭", ["yu"], ["sato(su)"]],
  ["輸", ["yu"], []],
  ["癒", ["yu"], ["i(eru)", "i(yasu)"]],
  ["唯", ["yui", "[i]"], []],
  ["友", ["yuu"], ["tomo"]],
  ["有", ["yuu", "u"], ["a(ru)"]],
  ["勇", ["yuu"], ["isa(mu)"]],
  ["幽", ["yuu"], []],
  ["悠", ["yuu"], []],
  ["郵", ["yuu"], []],
  ["湧", ["yuu"], ["wa(ku)"]],
  ["猶", ["yuu"], []],
  ["裕", ["yuu"], []],
  ["遊", ["yuu", "[yu]"], ["aso(bu)"]],
  ["雄", ["yuu"], ["o", "osu"]],
  ["誘", ["yuu"], ["saso(u)"]],
  ["憂", ["yuu"], ["ure(eru)", "ure(i)", "u(i)"]],
  ["融", ["yuu"], []],
  ["優", ["yuu"], ["yasa(shii)", "sugu(reru)"]],
  ["与", ["yo"], ["ata(eru)"]],
  ["予", ["yo"], []],
  ["余", ["yo"], ["ama(ru)", "ama(su)"]],
  ["誉", ["yo"], ["homa(re)"]],
  ["預", ["yo"], ["azu(keru)", "azu(karu)"]],
  ["幼", ["yoo"], ["osana(i)"]],
  ["用", ["yoo"], ["mochi(iru)"]],
  ["羊", ["yoo"], ["hitsuji"]],
  ["妖", ["yoo"], ["aya(shii)"]],
  ["洋", ["yoo"], []],
  ["要", ["yoo"], ["kaname", "i(ru)"]],
  ["容", ["yoo"], []],
  ["庸", ["yoo"], []],
  ["揚", ["yoo"], ["a(geru)", "a(garu)"]],
  [
    "揺",
    ["yoo"],
    [
      "yu(reru)",
      "yu(ru)",
      "yu(ragu)",
      "yu(rugu)",
      "yu(suru)",
      "yu(saburu)",
      "yu(suburu)",
    ],
  ],
  ["葉", ["yoo"], ["ha"]],
  ["陽", ["yoo"], []],
  ["溶", ["yoo"], ["to(keru)", "to(kasu)", "to(ku)"]],
  ["腰", ["yoo"], ["koshi"]],
  ["様", ["yoo"], ["sama"]],
  ["瘍", ["yoo"], []],
  ["踊", ["yoo"], ["odo(ru)", "odo(ri)"]],
  ["窯", ["yoo"], ["kama"]],
  ["養", ["yoo"], ["yashina(u)"]],
  ["擁", ["yoo"], []],
  ["謡", ["yoo"], ["utai", "uta(u)"]],
  ["曜", ["yoo"], []],
  ["抑", ["yoku"], ["osa(eru)"]],
  ["沃", ["yoku"], []],
  ["浴", ["yoku"], ["a(biru)", "a(biseru)"]],
  ["欲", ["yoku"], ["hos(suru)", "ho(shii)"]],
  ["翌", ["yoku"], []],
  ["翼", ["yoku"], ["tsubasa"]],
  ["拉", ["ra"], []],
  ["裸", ["ra"], ["hadaka"]],
  ["羅", ["ra"], []],
  ["来", ["rai"], ["ku(ru)", "kita(ru)", "kita(su)"]],
  ["雷", ["rai"], ["kaminari"]],
  ["頼", ["rai"], ["tano(mu)", "tano(moshii)", "tayo(ru)"]],
  ["絡", ["raku"], ["kara(mu)", "kara(maru)", "kara(meru)"]],
  ["落", ["raku"], ["o(chiru)", "o(tosu)"]],
  ["酪", ["raku"], []],
  ["辣", ["ratsu"], []],
  ["乱", ["ran"], ["mida(reru)", "mida(su)"]],
  ["卵", ["ran"], ["tamago"]],
  ["覧", ["ran"], []],
  ["濫", ["ran"], []],
  ["藍", ["ran"], ["ai"]],
  ["欄", ["ran"], []],
  ["吏", ["ri"], []],
  ["利", ["ri"], ["ki(ku)"]],
  ["里", ["ri"], ["sato"]],
  ["理", ["ri"], []],
  ["痢", ["ri"], []],
  ["裏", ["ri"], ["ura"]],
  ["履", ["ri"], ["ha(ku)"]],
  ["璃", ["ri"], []],
  ["離", ["ri"], ["hana(reru)", "hana(su)"]],
  ["陸", ["riku"], []],
  ["立", ["ritsu", "[ryuu]"], ["ta(tsu)", "ta(teru)"]],
  ["律", ["ritsu", "[richi]"], []],
  ["慄", ["ritsu"], []],
  ["略", ["ryaku"], []],
  ["柳", ["ryuu"], ["yanagi"]],
  ["流", ["ryuu", "[ru]"], ["naga(reru)", "naga(su)"]],
  ["留", ["ryuu", "[ru]"], ["to(meru)", "to(maru)"]],
  ["竜", ["ryuu"], ["tatsu"]],
  ["粒", ["ryuu"], ["tsubu"]],
  ["隆", ["ryuu"], []],
  ["硫", ["ryuu"], []],
  ["侶", ["ryo"], []],
  ["旅", ["ryo"], ["tabi"]],
  ["虜", ["ryo"], []],
  ["慮", ["ryo"], []],
  ["了", ["ryoo"], []],
  ["両", ["ryoo"], []],
  ["良", ["ryoo"], ["yo(i)"]],
  ["料", ["ryoo"], []],
  ["涼", ["ryoo"], ["suzu(shii)", "suzu(mu)"]],
  ["猟", ["ryoo"], []],
  ["陵", ["ryoo"], ["misasagi"]],
  ["量", ["ryoo"], ["haka(ru)"]],
  ["僚", ["ryoo"], []],
  ["領", ["ryoo"], []],
  ["寮", ["ryoo"], []],
  ["療", ["ryoo"], []],
  ["瞭", ["ryoo"], []],
  ["糧", ["ryoo", "[roo]"], ["kate"]],
  ["力", ["ryoku", "riki"], ["chikara"]],
  ["緑", ["ryoku", "[roku]"], ["midori"]],
  ["林", ["rin"], ["hayashi"]],
  ["厘", ["rin"], []],
  ["倫", ["rin"], []],
  ["輪", ["rin"], ["wa"]],
  ["隣", ["rin"], ["tona(ru)", "tonari"]],
  ["臨", ["rin"], ["nozo(mu)"]],
  ["瑠", ["ru"], []],
  ["涙", ["rui"], ["namida"]],
  ["累", ["rui"], []],
  ["塁", ["rui"], []],
  ["類", ["rui"], ["tagu(i)"]],
  ["令", ["rei"], []],
  ["礼", ["rei", "rai"], []],
  [
    "冷",
    ["rei"],
    [
      "tsume(tai)",
      "hi(eru)",
      "hi(ya)",
      "hi(yasu)",
      "hi(yakasu)",
      "sa(meru)",
      "sa(masu)",
    ],
  ],
  ["励", ["rei"], ["hage(mu)", "hage(masu)"]],
  ["戻", ["rei"], ["modo(ru)", "modo(su)"]],
  ["例", ["rei"], ["tato(eru)"]],
  ["鈴", ["rei", "rin"], ["suzu"]],
  ["零", ["rei"], []],
  ["霊", ["rei", "ryoo"], ["tama"]],
  ["隷", ["rei"], []],
  ["齢", ["rei"], []],
  ["麗", ["rei"], ["uruwa(shii)"]],
  ["暦", ["reki"], ["koyomi"]],
  ["歴", ["reki"], []],
  ["列", ["retsu"], []],
  ["劣", ["retsu"], ["oto(ru)"]],
  ["烈", ["retsu"], []],
  ["裂", ["retsu"], ["sa(ku)", "sa(keru)"]],
  ["恋", ["ren"], ["ko(u)", "koi", "koi(shii)"]],
  ["連", ["ren"], ["tsura(naru)", "tsura(neru)", "tsu(reru)"]],
  ["廉", ["ren"], []],
  ["練", ["ren"], ["ne(ru)"]],
  ["錬", ["ren"], []],
  ["呂", ["ro"], []],
  ["炉", ["ro"], []],
  ["賂", ["ro"], []],
  ["路", ["ro"], ["ji"]],
  ["露", ["ro", "[roo]"], ["tsuyu"]],
  ["老", ["roo"], ["o(iru)", "fu(keru)"]],
  ["労", ["roo"], []],
  ["弄", ["roo"], ["moteaso(bu)"]],
  ["郎", ["roo"], []],
  ["朗", ["roo"], ["hoga(raka)"]],
  ["浪", ["roo"], []],
  ["廊", ["roo"], []],
  ["楼", ["roo"], []],
  ["漏", ["roo"], ["mo(ru)", "mo(reru)", "mo(rasu)"]],
  ["籠", ["roo"], ["kago", "ko(moru)"]],
  ["六", ["roku"], ["mu", "mu(tsu)", "mut(tsu)", "[mui]"]],
  ["録", ["roku"], []],
  ["麓", ["roku"], ["fumoto"]],
  ["論", ["ron"], []],
  [
    "和",
    ["wa", "[o]"],
    ["yawa(ragu)", "yawa(rageru)", "nago(mu)", "nago(yaka)"],
  ],
  ["話", ["wa"], ["hana(su)", "hanashi"]],
  ["賄", ["wai"], ["makana(u)"]],
  ["脇", [], ["waki"]],
  ["惑", ["waku"], ["mado(u)"]],
  ["枠", [], ["waku"]],
  ["湾", ["wan"], []],
  ["腕", ["wan"], ["ude"]],
];
